### ISSUE TITLE
What techniques are available with ZeRO?

### ISSUE THREAD

**Issue by hyunwoongko** [microsoft/DeepSpeed#1289]
- PLD + ZeRO
- MoQ + ZeRO
- Transformer Kernel + ZeRO
- Sparse Attention + ZeRO

Are the above combinations available?
How many more combinations can I use? (e.g. Transformer Kernel + PLD + MoQ + ZeRO)

It would be great to have a table organized for these combinations. For example, Sparse Attention and Transformer Kernel cannot be used together, or 1-bit Adam and ZeRO cannot be used together.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @hyunwoongko,

- MoQ + ZeRO is possible as the MoQ is only happening at the optimizer step and is mainly quantizing the weight parameters without changing anything on the training process. 
- ZeRO + Sparse-Attention is possible since it mainly changes the operation for the attention in forward and backward and can be easily combined with ZeRO optimization. 
- ZeRO + Transformer kernel can be possible when the kernels can be injected in the model. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/reyazda/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/reyazda/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | ZERO | Transformer-Kernel | Sparse-Attention
-- | -- | -- | --
Transformer-Kernel | YES |   |  
Sparse-Attention | YES | NO |  
MoQ | YES | YES | YES



</body>

</html>


Thanks,
Reza

**Comment by hyunwoongko** [comment]
Thanks your easy explanation. How about PLD? is PLD available when I use ZeRO optimization together?

**Comment by minjiazhang** [comment]
Hi @hyunwoongko,

PLD has not been integrated together with ZeRO yet. However, we do support running PLD with data parallelism (e.g., PyTorch DDP). It is on our roadmap to combine ZeRO and PLD. 

Best,
Minjia

**Comment by hyunwoongko** [comment]
@minjiazhang Thank you !
