### ISSUE TITLE
[BUG]param in flight during save_fp16_model

### ISSUE THREAD

**Issue by william-trustlab** [microsoft/DeepSpeed#1351]
**Describe the bug**
While running a HuggingFace Trainer with deepspeed (config described below), I'm encountering an error in which saving parameters in mixed precision mode attempts to partition parameters in flight. How can I fix this?

**ds_report output**
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
async_io ............... [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/ubuntu/tech-backends/exp_env/lib/python3.8/site-packages/torch']
torch version .................... 1.9.0+cu102
torch cuda version ............... 10.2
nvcc version ..................... 10.1
deepspeed install path ........... ['/home/ubuntu/tech-backends/exp_env/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.5.2+86b948f, 86b948f, master
deepspeed wheel compiled w. ...... torch 1.9, cuda 10.2

**Screenshots**
AssertionError:  Parameter containing:
tensor([[ 0.0576,  0.0217,  0.0652,  ..., -0.0320,  0.0302, -0.0098],
        [-0.1629,  0.0435, -0.0158,  ..., -0.0225,  0.1197,  0.0337],
        [-0.0600,  0.1420, -0.0242,  ..., -0.0138, -0.1149, -0.0372],
        ...,
        [-0.0003,  0.1950,  0.0771,  ..., -0.0522,  0.0227, -0.0936],
        [ 0.0039,  0.0035, -0.0561,  ...,  0.0408,  0.0249, -0.0991],
        [-0.1931, -0.0790, -0.1222,  ...,  0.0063, -0.0225, -0.0494]],
       device='cuda:0', requires_grad=True) Cannot parititon a param in flight

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count: 1 Tesla T4
 - Python version: 3.7

**Launcher context**
Running with deepspeed config in HuggingFace Trainer:
```json
{
                "fp16": {
                    "enabled": "auto",
                    "loss_scale": 0,
                    "loss_scale_window": 1000,
                    "initial_scale_power": 16,
                    "hysteresis": 2,
                    "min_loss_scale": 1
                },
                "optimizer": {
                    "type": "AdamW",
                    "params": {
                        "lr": "auto",
                        "betas": "auto",
                        "eps": "auto",
                        "weight_decay": "auto"
                    }
                },
                "scheduler": {
                    "type": "WarmupLR",
                    "params": {
                        "warmup_min_lr": "auto",
                        "warmup_max_lr": "auto",
                        "warmup_num_steps": "auto"
                    }
                },

                "zero_optimization": {
                    "stage": 3,
                    "offload_optimizer": {
                        "device": "cpu",
                        "pin_memory": true
                    },
                    "offload_param": {
                        "device": "cpu",
                        "pin_memory": true
                    },
                    "overlap_comm": true,
                    "contiguous_gradients": true,
                    "sub_group_size": 1e9,
                    "reduce_bucket_size": "auto",
                    "stage3_prefetch_bucket_size": "auto",
                    "stage3_param_persistence_threshold": "auto",
                    "stage3_max_live_parameters": 1e9,
                    "stage3_max_reuse_distance": 1e9,
                    "stage3_gather_fp16_weights_on_model_save": true         
                },

                "gradient_accumulation_steps": "auto",
                "gradient_clipping": "auto",
                "steps_per_print": 2000,
                "train_batch_size": "auto",
                "train_micro_batch_size_per_gpu": "auto",
                "wall_clock_breakdown": false
            }
```

**Comment by tjruwase** [comment]
@william-trustlab, thanks for reporting this error. Can you please share the command-line as well?

**Comment by william-trustlab** [comment]
It's just `python script.py`, within it the training occurs within this:
`train_args = TrainingArguments(
    str(Path.home())
    + "PATHDIR",
    # evaluation_strategy="steps",
    save_strategy="steps",
    save_steps=100,
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    # per_device_eval_batch_size=16,
    gradient_accumulation_steps=10,
    num_train_epochs=5,
    weight_decay=0.01,
    # load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    label_names="label",
    deepspeed=deepspeed_config,
)
trainer = Trainer(
    model,
    train_args,
    train_dataset=encoded_dataset["train"],
    # eval_dataset=encoded_dataset["valid"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)
trainer.train(resume_from_checkpoint=False)
`

**Comment by tjruwase** [comment]
Sorry for not being clearer earlier, I asked for the command-line so that I can repro the issue. Unfortunately, your reply does not provide required information for repro. Can you share `script.py`? Is it a standard HF script? Thanks.

**Comment by tacerdi** [comment]
@william-trustlab did you figure out how to solve this issue?

**Comment by tjruwase** [comment]
@tacerdi, are you seeing a similar issue? Can you share details to help repro?

**Comment by tacerdi** [comment]
I'm running DeepSpeed integrated in HuggingFace Trainer with standard configurations. The error is thrown right when the model weights are saved at checkpoint-500 (which is the first checkpoint to save anything)

Here is the whole error message:

`~/.local/lib/python3.8/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1340                     self.control = self.callback_handler.on_step_end(args, self.state, self.control)
   1341 
-> 1342                     self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
   1343 
   1344                 if self.control.should_epoch_stop or self.control.should_training_stop:

~/.local/lib/python3.8/site-packages/transformers/trainer.py in _maybe_log_save_evaluate(self, tr_loss, model, trial, epoch, ignore_keys_for_eval)
   1445 
   1446         if self.control.should_save:
-> 1447             self._save_checkpoint(model, trial, metrics=metrics)
   1448             self.control = self.callback_handler.on_save(self.args, self.state, self.control)
   1449 

~/.local/lib/python3.8/site-packages/transformers/trainer.py in _save_checkpoint(self, model, trial, metrics)
   1505 
   1506         output_dir = os.path.join(run_dir, checkpoint_folder)
-> 1507         self.save_model(output_dir)
   1508         if self.deepspeed:
   1509             # under zero3 model file itself doesn't get saved since it's bogus! Unless deepspeed

~/.local/lib/python3.8/site-packages/transformers/trainer.py in save_model(self, output_dir)
   1886                 # if false it will not be saved.
   1887                 # This must be called on all ranks
-> 1888                 self.deepspeed.save_fp16_model(output_dir, WEIGHTS_NAME)
   1889 
   1890         elif self.args.should_save:

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in save_fp16_model(self, save_dir, save_filename)
   2525             if self.zero_gather_fp16_weights_on_model_save():
   2526                 # consolidation is expensive in time and memory and therefore isn't a default
-> 2527                 state_dict = self._zero3_consolidated_fp16_state_dict()
   2528             else:
   2529                 # the model will be bogus if not consolidated so don't confuse the user by saving it

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in _zero3_consolidated_fp16_state_dict(self)
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)
-> 2502         get_layer_state_dict(self.module, prefix="")
   2503         see_memory_usage("after get_layer_state_dict", force=False)
   2504 

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2497             for name, child in module.named_children():
   2498                 if child is not None:
-> 2499                     get_layer_state_dict(child, prefix + name + ".")
   2500 
   2501         see_memory_usage("before get_layer_state_dict", force=False)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py in get_layer_state_dict(module, prefix)
   2492                     for name, buf in module.named_buffers(recurse=False):
   2493                         if buf is not None and name not in module._non_persistent_buffers_set:
-> 2494                             state_dict[prefix + name] = buf.detach().cpu()
   2495             #see_memory_usage("after GatheredParameters", force=True)
   2496 

~/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py in __exit__(self, *exc)
   1221         for h in handles:
   1222             h.wait()
-> 1223         self.params[0].partition(param_list=self.params, has_been_updated=True)

~/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py in partition(param_list, hierarchy, has_been_updated)
    586             if param_list is None:
    587                 param_list = [cls]
--> 588             self._partition(param_list, has_been_updated=has_been_updated)
    589 
    590         def reduce_gradients_at_owner(param_list=None, hierarchy=0):

~/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py in _partition(self, param_list, force, has_been_updated)
    691             #print_rank_0(f"Before Partitioning Param {param.ds_id}")
    692             #self._param_status(param)
--> 693             self._partition_param(param, has_been_updated=has_been_updated)
    694             param.ds_status = ZeroParamStatus.NOT_AVAILABLE
    695             #if param.ds_tensor is not None:

~/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py in _partition_param(self, param, buffer, has_been_updated)
    700 
    701     def _partition_param(self, param, buffer=None, has_been_updated=False):
--> 702         assert param.ds_status is not ZeroParamStatus.INFLIGHT, f" {param} Cannot parititon a param in flight"
    703 
    704         global reuse_buffers

AssertionError:  Parameter containing:
tensor([[ 0.0807, -0.0452,  0.0337,  ...,  0.0142, -0.0514, -0.0598],
        [ 0.0396, -0.0030, -0.0003,  ..., -0.0150, -0.0271, -0.0134],
        [-0.0103, -0.0283, -0.0284,  ..., -0.0183,  0.0501, -0.0472],
        ...,
        [ 0.0012, -0.0477,  0.0412,  ...,  0.0428,  0.0287, -0.0175],
        [-0.0115,  0.0192, -0.0320,  ...,  0.0472, -0.0517, -0.0413],
        [-0.0279,  0.0458,  0.0085,  ..., -0.0220,  0.0403, -0.0330]],
       device='cuda:0', requires_grad=True) Cannot parititon a param in flight`

**Comment by tjruwase** [comment]
@tacerdi, thanks for sharing the error log. However, I need a bit more details as I would like to reproduce this issue on my side. Can you provide me the command-line for launching the run? This would also help identify the training script in the HF codebase. Thanks.

**Comment by tjruwase** [comment]
> It's just `python script.py`, within it the training occurs within this: `train_args = TrainingArguments( str(Path.home()) + "PATHDIR", # evaluation_strategy="steps", save_strategy="steps", save_steps=100, learning_rate=2e-5, per_device_train_batch_size=8, # per_device_eval_batch_size=16, gradient_accumulation_steps=10, num_train_epochs=5, weight_decay=0.01, # load_best_model_at_end=True, metric_for_best_model="accuracy", label_names="label", deepspeed=deepspeed_config, ) trainer = Trainer( model, train_args, train_dataset=encoded_dataset["train"], # eval_dataset=encoded_dataset["valid"], tokenizer=tokenizer, compute_metrics=compute_metrics, ) trainer.train(resume_from_checkpoint=False) `

@william-trustlab, are you able to share the full script.py? Thanks.

**Comment by tjruwase** [comment]
Closing for lack of response. Please re-open as appropriate.
