### ISSUE TITLE
[BUG] max_seq_length paramter missing in DeepSpeedTransformerConfig

### ISSUE THREAD

**Issue by delock** [microsoft/DeepSpeed#1364]
**Describe the bug**
In comments of DeepSpeedTransformerConfig, there is a parameter max_seq_length, however it is not in __init__ function

**To Reproduce**
1. https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/ops/transformer/transformer.py
2. Search for DeepSpeedTransformerConfig
3. In comments see "max_seq_length: The sequence-length of the model being trained with DeepSpeed"
4. Goto __init__, there is no parameter max_seq_length
5. Goto TransformerConfig, there is no parameter max_seq_length either

**Expected behavior**
max_seq_length should appear in paramter list

**Comment by RezaYazdaniAminabadi** [comment]
Hi @delock,

Yes, you are right. Initially, we added this parameter to allocate the buffers properly, however, we later remove this as the sequence-length can be a dynamic parameter. So, we allocate the buffers based on the max_sequence_length that we see during the training: https://github.com/microsoft/DeepSpeed/blob/master/csrc/transformer/ds_transformer_cuda.cpp#L713-L720

Do you have any thought on where/why this parameter can be useful? Otherwise, we can remove it.

Thanks,
Reza

**Comment by delock** [comment]
Thanks!  If it is no longer needed better remove from documentation.
