### ISSUE TITLE
[QUESTION] Clarifying DeepSpeed-Inference

### ISSUE THREAD

**Issue by gahdritz** [microsoft/DeepSpeed#1610]
Some questions about DeepSpeed-Inference:

1. In the documentation for DeepSpeed-Inference (e.g. [here](https://www.deepspeed.ai/tutorials/inference-tutorial/)), it is claimed that the functionality works specifically for large transformer models. Obviously, certain components, like the optimized kernels, only apply if your model is a standard HuggingFace-style transformer. Are the other features (e.g. inference-time model parallelism) more general? Can I use them on any PyTorch model, and without a HuggingFace `pipeline`?

2. Am I correct to assume that DeepSpeed-Inference model parallelism would not improve the memory performance of a memory-intensive model whose parameters account for only a small portion of its memory consumption (e.g. a relatively small model (~100M parameters) with extremely large intermediate activations)?

3. Assuming that the answer to (1) is yes, I've experimented a little with simple MLP's. DeepSpeed-Inference appears to run a full copy of the model in parallel on each GPU (rather than splitting it up between them, as I'd expect). Here's the code I used for those experiments:

```python
import os

import torch
import deepspeed

torch.manual_seed(42)

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

NUM_LAYERS = 9000
LAYER_DIM = 500

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.ml = torch.nn.ModuleList()
        for _ in range(NUM_LAYERS):
            self.ml.append(torch.nn.Linear(LAYER_DIM, LAYER_DIM))

    def forward(self, x):
        for l in self.ml:
            x = l(x)

        return x


model = Model().eval()

ds_engine = deepspeed.init_inference(
    model,
    mp_size=world_size,
    checkpoint=None,
    replace_method=None,
)
model = ds_engine.module

with torch.no_grad():
    example = torch.rand((500, 500)).to(f"cuda:{local_rank}")
    out = model(example)

if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
    print(out)
```

When I ran this successively with `deepspeed --num_gpus 2 experiment.py`, increasing `NUM_LAYERS` until I ran out of memory, I ran into the same upper bound as when I ran the same experiment on a single GPU using vanilla PyTorch, even though I'd expect the DeepSpeed-Inference version to be able to handle values approximately twice as large. Am I doing something wrong?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @gahdritz 
Thanks for using DeepSpeed-Inference, and raising these interesting questions.
I try to answer your questions below:
1. Yes, we have tried to show the inference module in DeepSpeed mostly on HF models. Except the kernels, which requires some modification for supporting different transformer-type models, the rest can be used with different PyTorch models. On the other hand, you need to provide an injection-policy when using the model-parallelism as what you need to use in your specific example. That being said, I am preparing a tutorial on how to specify this so that you can understand what this policy exactly means.
2. I am not sure if I completely understand your question. But, if you mean that you use a very large batch size, then you can use parallelism across batch (which is better than model-parallelism since you have smaller model). Or if the sequence-length is large, then yes you are right that model-parallelism cannot help you since the attention computation remains the same.
3. The main reason you did not see any improvement with DeepSpeed is that you require to pass in a policy, so that we can inject parallelism properly (like in this [example](https://github.com/microsoft/DeepSpeedExamples/blob/inference/General-TP-examples/inference/huggingface/test-roberta.py#L22)). For this, you need to modify your example a bit:
```
class mlp(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.m1 = torch.nn.Linear(LAYER_DIM, LAYER_DIM)
        self.m2 = torch.nn.Linear(LAYER_DIM, LAYER_DIM)

    def forward(self, x):
            x = self.m2(self.m1(x))

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.ml = torch.nn.ModuleList()
        for _ in range(NUM_LAYERS//2):
            self.ml.append(mlp())
        if (2 * (NUM_LAYERS//2)) < NUM_LAYERS:
            self.ml.append(torch.nn.Linear(LAYER_DIM, LAYER_DIM))

    def forward(self, x):
        for l in self.ml:
            x = l(x)

        return x

model = Model().eval()

ds_engine = deepspeed.init_inference(
    model,
    mp_size=world_size,
    checkpoint=None,
    replace_method=None,
    injection_policy={ml: ('mlp.m2')},
)
model = ds_engine.module

```

**Comment by gahdritz** [comment]
Thanks! This answers all of my questions. I look forward to that policy guide.
