### ISSUE TITLE
some questions about the source code

### ISSUE THREAD

**Issue by sjtusmartboy** [microsoft/DeepSpeed#169]
I'm pretty interested in the implementation of the ZeRO optimizer because the work is really beyond words. Yet I find some points I cannot understand when reading the source code, so I'm here to ask for some help to understand the DeepSpeed better.

1. All through the project, I can find the implementation of Gradient Partitioning and Parameter Partitioning [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/pt/deepspeed_zero_optimizer.py#L153) because partitioning `param_group['params']` would involve partitioning both the weights(p.data) and gradients(p.grads),  but I cannot find where Optimizer State Partitioning is. 

2. [shard_list](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/pt/deepspeed_zero_optimizer.py#L411) seems to be a temporary variable in the for-loop, which means that it will be discarded for every loop, so what's the meaning of `dist.all_gather` [here](dist.all_gather)? It seems to have something to do with pipeline. Would you please elaborate it?

3. What's the meaning of parameter `allgather_size` for the `FP16_DeepSpeedZeroOptimizer`

Would you please also share the presentation slides on the design and implementation of ZeRO ? Thanks a million !

**Comment by samyam** [comment]
@sjtusmartboy Thank you for your interest in ZeRO and DeepSpeed. Let me try to answer your questions

1. DeepSpeed currently only implements ZeRO stage 1 which means it only does Optimizer State Partitioning but not Gradient or Parameter partitioning. To do so, by only passing the parameters that belongs to a particular partition to the param_group['params'] so that when an optimizer like ADAM initializes its optimizer states, it only does so for the parameters that param_group['params'] is pointing to. Here is the relevant code:

            data_parallel_partitions = self.get_data_parallel_partitions(
                self.fp16_groups_flat[i])
            self.parallel_partitioned_fp16_groups.append(data_parallel_partitions)

            # a partition of the fp32 master weights that will be updated by this process
            self.single_partition_of_fp32_groups.append(
                self.parallel_partitioned_fp16_groups[i]
                [partition_id].clone().float().detach())

            # modify optimizer of have flat master weight
            self.single_partition_of_fp32_groups[
                i].requires_grad = True  # keep this in case internal optimizer uses it
            param_group['params'] = [self.single_partition_of_fp32_groups[i]]


The single_partition_of_fp32_groups only contains those parameters that belong to this partition, so later when the adam optimizer calls its step function, it will only instantiate the momentum and variance for these parameters and compute updates for it.

2. Since each GPU only updates the parameters in its partition, each GPU needs to broadcast its parameters to all the other GPUs. Each GPU broadcasting its parameters is collectively an all_gather operation. 

Each element of the shard_list is a tensor pointing to parameters that belong to different partitions. Even though shard_list is a temporary variable, the underlying data that its elements are pointing are not. By doing an all_gather on the shard_list, we are broadcasting the updated parameters from each partition to all the other partition.

3. The allgather_size is used to break down what would otherwise be a single large all_gather to several smaller ones of size allgather_size. The all_gather operation requires temporary buffers proportional is size to the number of elements in the allgather. So if the number of elements is too large, it can run out of memory. We use allgather_size to break a large all_gather into several smaller ones. 

Here is a link to a talk on DeepSpeed and ZeRO at NVIDIA GTC: https://www.nvidia.com/en-us/gtc/session-catalog/?search=S22646%20

**Comment by sjtusmartboy** [comment]
@samyam Thanks for your patient reply and now I come to know the system better. 

For the first question, the Optimizer State parameter defined in the torch optimizer such as adam has the same size with the param_group['params'] that has been partitioned in the FP16_DeepSpeedZeroOptimizer, so the Optimizer State is also partitioned at the same time. 

For the second question, FP16_DeepSpeedZeroOptimizer makes use of shallow copy mechanism in a very smart way to gather the weight from other partitions.

And for the third question, is allgather_size the key to achieving  performance-efficient constant-size fused buffer referenced in the `5.4 CB: Constant Size Buffers` of the paper by limiting the allgather_size that all_gather requires when receiving other partitions? Also I notice that both `MEMORY_OPT_ALLREDUCE_SIZE` and `allgather_size` in the source code have the default value of 500000000, do they have the same meaning and same usage?

Still another two questions on your code.

1. It seems that `buffered_allreduce_fallback` involves the all_reduce or all_gather of two types of grad, type CSRTensor or the other types. The grad_data is wrapped with CSRTensor if it is of `torch.nn.Embedding` type. Also I notice that  `dist.all_gather` is used in `def csr_all_gather` for CSRTensor while `dist.all_reduce` is used in `def allreduce_bucket` for non-CSRTensor. Would you please explain what makes this difference? For the non-CSRTensor, I guess it's the result of data parallelism, so we make dist.all_reduce sum and average the reduced result by the world size. 

`

    def buffered_allreduce_fallback(self, grads=None, elements_per_buffer=500000000):
        grads = []
        for param_name, param in self.module.named_parameters():
            if param.grad is not None:
                grad_data = param.grad.data
                param_name_root = param_name.split('.', 1)[0]
                if self.sparse_gradients_enabled(
                ) and param_name_root in self.csr_tensor_module_names:
                    grads.append(CSRTensor(grad_data))
                else:
                    grads.append(grad_data)

        split_buckets = split_half_float_double_csr(grads)

        for i, bucket_tuple in enumerate(split_buckets):
            bucket_type, bucket = bucket_tuple
            if bucket_type == CSRTensor.type():
                self.csr_allreduce_no_retain(bucket)
            else:
                self.allreduce_no_retain(bucket, numel_per_bucket=elements_per_buffer)

`

2. It's said in the paper that 

> Therefore, during the forward propagation it needs to receives the parameters for all the other partitions. However, this can be pipelined to avoid the memory overhead.

 I wonder if it is the second stage of work for the parameter partitioning. We are really looking forward to this stage.

**Comment by sjtusmartboy** [comment]
@samyam I come to understand the reason of using all_gather in CSRTensor. In the data parallelism, different process will have totally different  part of the weight that should be update. So we just all_gather them in the list of indices_device_list and in the list of values_device_list and then make average of these gradients from different devices. `csr.to_dense()` function will be responsible for calculating the sum of different values if their indices in the  indices_device_list happen to be the same.

**Comment by samyam** [comment]
@sjtusmartboy You are right. allgather_size and reduce_bucket_size are examples of CSB. The reduce_bucket_size controls the size of the dist.all_reduce for gradient averaging while allgather_size controls the size of dist.allgather in the step.

You are also correct on 1 and 2. The parameter partitioning is the third stage of zero. We will be releasing stage 2 before that which will do gradient partitioning. Gradient partitioning will double the model size that can be trained compared to Stage 1, and it will also allow for running larger batch sizes.

**Comment by samyam** [comment]
Seems like all the questions have been answered here. Closing the issue. @sjtusmartboy , please feel free to reopen if you have any additional questions, comments, or feedback.
