### ISSUE TITLE
[BUG]DeepSpeedCPUAdam becomes much slower after the commit 8abdaee

### ISSUE THREAD

**Issue by Dido0o0** [microsoft/DeepSpeed#1697]
In my model, the model training speed is much slower after the version is updated from 0.5.3 to 0.5.8.
After comparison, I found out that the slowed module is 'optimizer_step' part, which is using DeepSpeedCPUAdam -> self.step -> self.ds_opt_adam.adam_update_copy

And I made detailed test between version 0.5.3 to 0.5.8, the latency result is: 0.5.3 = 0.5.4 << 0.5.5 = 0.5.7 = 0.5.9.
Observing the commit histories related to adam_update_copy(), I guess the performance degradation is caused by the commit 8abdaee2430497438729daeded370db8a0e03c9b

The referenced data on my custom model is as following:
Version 0.5.8
[INFO] [logging.py:69:log_dist] [Rank 0] rank=0 time (ms) | optimizer_allgather: 1.30 | optimizer_gradients: 10.25 | optimizer_step: 1321.71

Version 0.5.3
[INFO] [logging.py:68:log_dist] [Rank 0] rank=0 time (ms) | optimizer_allgather: 1.28 | optimizer_grad    ients: 10.05 | optimizer_step: 86.30

**Comment by RezaYazdaniAminabadi** [comment]
Hi @Dido0o0 

Yest, there was some performance degradation due to that commit that you pointed. I tried to solve this issue (which was mentioned in another post too https://github.com/microsoft/DeepSpeed/issues/1635) at this commit: https://github.com/microsoft/DeepSpeed/commit/259936a76c0a2baafdffabbef8b0e2843f969d48. It is included in version 5.10. Could you please try the newer version to see if the issue is resolved?
Thanks,
Reza
