### ISSUE TITLE
Need help running DeepSpeed distributed on-premises with containers

### ISSUE THREAD

**Issue by dav-ell** [microsoft/DeepSpeed#174]
I've followed the steps in the [Azure guide](https://www.deepspeed.ai/tutorials/azure/), with some minor adjustments:

- I can't create a user `deepspeed` on each host, I need to use an existing user `myuser`.
- I'm using my own training script, not one in the examples.

I can run training locally in the deepspeed container, but when I go to make it distributed I get very lost.

I launched the deepspeed container on the master host using the command:

```bash
sudo docker run -it --gpus all --name deepspeed --ipc=host -d \
    -v /home/myuser:/home/myuser \
    deepspeed/deepspeed:latest bash
```

To run commands in the container I use:

```bash
sudo docker exec -it deepspeed bash
```

I've made the master host able to talk to every other host without requiring a password by exchanging keys via `ssh-copy-id [host]` from within the deepspeed container. I've written a hostfile with the following contents (keeping it simple):

```
host-1 slots=1
```

When I go to run my code, I use the command:

```bash
deepspeed pretrain.py --deepspeed --deepspeed_config ds_cfg.json 
```

This gives me the error:

```
host-1: /usr/bin/python: No module named deepspeed.pt
pdsh@id: host-1: ssh exited with exit code 1
```

I don't really know where to go from here. As far as I can tell, there's no way for `host-1` to be able to run anything inside the deepspeed container, unless I was connecting directly to the container when I ran `ssh`. But that doesn't seem to be what's happening in the Azure scripts. So what's the point of running deepspeed containers on any host but the master host? I'm missing something here.

**Comment by jeffra** [comment]
Hi @dav-ell, thanks for using DeepSpeed and our azure tutorial.

The "No module named deepspeed.pt" error makes me wonder if deepspeed is fully installed in your docker container. What happens if you run the following two commands inside the container.

* `which deepspeed`
  * On my system, which returns: `/usr/local/bin/deepspeed`
* `python -c "import deepspeed; print(deepspeed.__git_hash__)"`
  * On my system, this returns the commit hash of the installed version of deepspeed which should be something like: `20557f7`

Also you mentioned you can train locally in the container, I assume you were not using `deepspeed` launcher in this case? or where you just not using a hostfile in this case?

**Comment by jeffra** [comment]
@dav-ell any updates on this? did you resolve your issue? If not please re-open.

**Comment by dav-ell** [comment]
@jeffra Thanks for checking back in. I did not; I ended up, unfortunately, using PyTorch's regular distributed handling, and haven't tried deepspeed since.

**Comment by jeffra** [comment]
Sorry to hear that. Let us know if you want to try again and if you still have issues.
