### ISSUE TITLE
DeepSpeed Inference support for OPT

### ISSUE THREAD

**Issue by shijie-wu** [microsoft/DeepSpeed#1978]
Right now OPT (https://huggingface.co/docs/transformers/model_doc/opt) can only be supported via custom kernel injection policy. It would be great if there's official support. Thanks!

**Comment by comaniac** [comment]
I have the same requirement so I wrote a custom policy for OPT and it seems working (i.e., the inference engine was initialized successfully and I could see some `nvcc` commends which were for fused kernel compilation I guess?)

However when actual performing the inference, I got an error:

```
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/opt/modeling_opt.py", line 706, in forward
    return forward_call(*input, **kwargs)
TypeError:     forward() got an unexpected keyword argument 'layer_head_mask'return forward_call(*input, **kwargs)

TypeError: forward() got an unexpected keyword argument 'layer_head_mask'
        use_cache=use_cache,use_cache=use_cache,
TypeErrorTypeError: : forward() got an unexpected keyword argument 'layer_head_mask'forward() got an unexpected keyword argument 'layer_head_mask'
```

I dived into the code and found that this is because of the argument mismatch between the following two:
1. https://github.com/microsoft/DeepSpeed/blob/b666d5cd73b25e88afe9591f4e9c010e7219df44/deepspeed/ops/transformer/inference/transformer_inference.py#L622
2. https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L281

I have no idea how to improve ` DeepSpeedTransformerInference` to make sure its arguments are compatible with emerging models, tho.
