### ISSUE TITLE
[BUG]pip install doesn't work. Please help. 

### ISSUE THREAD

**Issue by kaustubhroy1995** [microsoft/DeepSpeed#2137]
**Describe the bug**
pip install not working for windows 10
**To Reproduce**
1. Go to Command Prompt
2. Type in 'pip install deepspeed'
3. Voila

**Expected behavior**
Install Deepspeed?

**System info (please complete the following information):**
 - OS: Windows 10 Pro
 - GPU: RTX 2060 Super
 - Screnshot of error
![Deepspeed_Issue](https://user-images.githubusercontent.com/110053115/181066192-61f030e3-1ce8-4fff-b9e5-f531744d1689.png)
 - Python version: 3.10

**Comment by jeffra** [comment]
I've repro'd your issue, will let you know when i have a fix

**Comment by jeffra** [comment]
I repro'd this on a windows box that does not have a GPU. Can you confirm that torch sees your gpu from windows?

Can you share the results of `torch.cuda.is_available()` and `torch.cuda.get_device_properties(0)`?

**Comment by hamzafar** [comment]
Hi @jeffra ,
I ran above torch commands on my windows, I can see access gpu inside my virtual environment. However deepspeed is not installed. 
![image](https://user-images.githubusercontent.com/6842017/202547197-7468adc3-7b5a-4665-a8a5-26373b2f969e.png)

**Comment by jeffra** [comment]
@hamzafar, can you share the results of this? For some reason torch might not be detecting your CUDA_HOME path.

`python -c "import torch.utils.cpp_extension; print(torch.utils.cpp_extension.CUDA_HOME)"`

**Comment by kaustubhroyvlabs** [comment]
I’m currently unable to access the machine I was working on. I’ll get back
to you by Wednesday.

Thanks for the reply

**Comment by hamzafar** [comment]
@jeffra I am getting None.
![image](https://user-images.githubusercontent.com/6842017/202555348-2ab38c1c-4f06-4bf4-b3e6-458c5617ddd8.png)

Could you recommend the solution?

**Comment by jeffra** [comment]
Interesting, do you have `nvcc` installed somewhere on your machine? This should come with the cuda toolkit (e.g, https://developer.nvidia.com/cuda-11.3.0-download-archive). If you have nvcc, can you share the version? e.g., `nvcc --version`

**Comment by hamzafar** [comment]
No I have not install nvcc in my machine. Ok let me install nvcc on my machine and will share it's version.

**Comment by jeffra** [comment]
I suspect that is the source of the issue here, DeepSpeed requires `nvcc` to be installed to compile our c++/cuda extensions. I just created a PR (https://github.com/microsoft/DeepSpeed/pull/2519) that adds a note about this to our requirements.

**Comment by hamzafar** [comment]
I have configured cuda on my machine but still same error.
![image](https://user-images.githubusercontent.com/6842017/202780542-3594e9c4-89f4-4496-a735-6358a2c58065.png)

**Comment by jeffra** [comment]
Interesting, glad to see `nvcc` is coming up okay. This error at install makes me think CUDA_HOME is still returning None from torch though. Does `python -c "import torch.utils.cpp_extension; print(torch.utils.cpp_extension.CUDA_HOME)"` still print None? Here's the logic that pytorch takes to find CUDA_HOME: https://github.com/pytorch/pytorch/blob/7ec8a4d2a26f717d0a4073e6005f9edfdd7ab641/torch/utils/cpp_extension.py#L86

Perhaps can you set `CUDA_HOME` to be where your cuda install is located? I see on Windows it says it defaults to `'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v*.*'`

**Comment by hamzafar** [comment]
System is not accessing the cuda runtime.
![image](https://user-images.githubusercontent.com/6842017/202782181-196813fc-420a-403c-ad51-85e16c1f6bb8.png)

**Comment by jeffra** [comment]
What version of torch do you have installed here? can you show me the exact `torch.__version__`? I just want to make sure torch cuda is aligned with cuda 10.0 you have installed.

**Comment by hamzafar** [comment]
It shows me `'1.13.0+cpu'`. It's strange I have install gpu version of pytorch

**Comment by hamzafar** [comment]
I will configure pytorch gpu, in different env hopefully it will work.

**Comment by hamzafar** [comment]
I have configured pytorch gpu. And getting new error while configuring deep speed.
![image](https://user-images.githubusercontent.com/6842017/202860051-701c70d9-2f8a-4640-adca-d44dd47d2a90.png)

**Comment by hamzafar** [comment]
> What version of torch do you have installed here? can you show me the exact `torch.__version__`? I just want to make sure torch cuda is aligned with cuda 10.0 you have installed.

Hi I have attached the screen shoot of the error. could you confirm that cuda is aligned?

**Comment by mrwyattii** [comment]
@hamzafar it looks like there is an error compiling for `sparse_attn` - I think this is expected on Windows due to there being no triton v1.0. Can you set the following environment variable and try running again? `DS_BUILD_SPARSE_ATTN=0`

**Comment by hamzafar** [comment]
@mrwyattii  thank you for recommending me solution. However, this time there is no luck
![image](https://user-images.githubusercontent.com/6842017/206006822-8fdb64f8-2dcc-4245-a9fd-57caf5b619b8.png)

**Comment by hamzafar** [comment]
@mrwyattii no luck again :)
![image](https://user-images.githubusercontent.com/6842017/206010349-432725e1-77ca-4c74-b7b9-102dcace872f.png)

**Comment by mrwyattii** [comment]
well looks like you are making it further into the install, so that's good news. I'm curious why you don't have permission to remove that directory. Can you try running with admin/root privileges and see if that addresses the permissions error?

**Comment by hamzafar** [comment]
I run anaconda PowerShell prompt as administrator and executed the pip install deepspeed command. However still getting Permission error.

**Comment by marcoseduardopm** [comment]
(Note: these steps are for the interference only mode)
After trying forever, I got it working. That's what I have done:
- Install the vs build tool 2019. If you already have it installed, repair it;
- Install Miniconda (if you haven't it already);
- Install CUDA 11.7 from https://developer.nvidia.com/cuda-11-7-0-download-archive ;
- Open "Anaconda Prompt (MiniConda3)";
- Create a python 3.10 env using: "conda create -n dsenv python=3.10.6"
- Activate the conda env using "conda activate dsenv";
- Install Pytorch and CUDA using: "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia";
- Close anaconda prompt;
- Open the Start -> "x64 Native Tools Command Prompt for VS 2019";
- Initialize conda on the Command prompt using "conda init cmd.exe";
- Reopen the  "x64 Native Tools Command Prompt for VS 2019" AS AN **ADMINISTRATOR**;
- Activate the conda env using "conda activate dsenv";
- Go to your root folder (could be c:\ or any other) and clone que DeepSpeed project "git clone https://github.com/microsoft/DeepSpeed";
- Depending on the fixes of the DeepSpeed repository, this step might or not be needed: Download here this file (https://drive.google.com/drive/folders/11EYHosWfDLrrVbniBLV1j82qeurpGlvX?usp=sharing) and replace the file at DeepSpeed\csrc\transformer\inference\csrc\pt_binding.cpp (see comments below);
- Go to the deepspeed folder using "cd DeepSpeed";
- Make 10 prayers to your god and try to install using "build_win.bat";
- A .whl will be created in the dist folder.


To install the generated .whl, just use:
For Python 3.10 version: pip install deepspeed-0.8.3+6eca037c-cp310-cp310-win_amd64.whl
For Pytohn 3.9 version: pip install deepspeed-0.8.3+4d27225f-cp39-cp39-win_amd64.whl

Extra Notes: 
Note: Tytorch version 1.13.1 with CUDA 11.7 also worked for me, but since it is an older version, I did not mention it in the steps above. If you need that version, install using "conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia"


About the replacement of file pt_binding.cpp: all I did was change lines  531, 532, 539, and 540:
New Lines 531 and 532:
                                     {static_cast<unsigned>(hidden_dim * Context::Instance().GetMaxTokenLenght()),
                                      static_cast<unsigned>(k * Context::Instance().GetMaxTokenLenght()),

New lines 539 and 540:
                                       {static_cast<unsigned>(hidden_dim * Context::Instance().GetMaxTokenLenght()),
                                        static_cast<unsigned>(k * Context::Instance().GetMaxTokenLenght()),


**For anyone that just want the final .whl to install using python, here it is (no prayers needed):** 
https://drive.google.com/drive/folders/117GSNHcJyzvMPTftl0aPBSwQVsU-z4bM?usp=sharing

**Comment by jomayeri** [comment]
Please check out the latest version of DeepSpeed for Windows compatibility.
