### ISSUE TITLE
[BUG] /tmp/torch_extensions directory created without global write permission

### ISSUE THREAD

**Issue by skiingpacman** [microsoft/DeepSpeed#2244]
**Describe the bug**
The directory (and associated sub-directories) /tmp/torch_extensions are created without global write permissions, e.g., only group and user have write permissions. On shared machines this can result in others being unable to run deepspeed as it fails at compile time.

Possibly related to this pytorch issue: https://github.com/pytorch/pytorch/issues/34238

Work around: `export TORCH_EXTENSIONS_DIR=/tmp/$USER/torch_extensions/`

**To Reproduce**
1. On a shared (linux) machine or cluster node user1 who is in group1 runs deepspeed, e.g. following https://www.deepspeed.ai/tutorials/inference-tutorial/
2. On the same (linux) machine or cluster node user2 who is in group2 tries to run deepspeed but gets permission error on export /tmp/torch_extensions/

**Expected behavior**
deepspeed either sets "other" write-permissions to the /tmp/torch_extensions/ directories or it creates separate directories per user.

**System info (please complete the following information):**
 - OS: 20.04.1-Ubuntu
 - GPU count and types: AWS cluster nodes with A100s

**Launcher context**
launched with command `deepspeed` at the command line

**Comment by jeffra** [comment]
Hi @skiingpacmanm, this behavior is (mostly) inherited from torch. I believe in earlier versions of torch they had this path default to `/tmp/torch_extensions`. However for a while now this defaults to the 'user' tmp path which is something like this (depending on system): https://github.com/pytorch/pytorch/blob/56a37ea1a6e89a8aa31abc888127ccac647b92d4/torch/_appdirs.py#L318-L322 and https://github.com/pytorch/pytorch/blob/56a37ea1a6e89a8aa31abc888127ccac647b92d4/torch/utils/cpp_extension.py#L1821

However, looking now I see we have left some code in our op builder that attempts to create the path at `/tmp/torch_extensions/op-name` if `TORCH_EXTENSIONS_DIR` isn't set. I think we can remove this block of code now since the path isn't even being used anymore in modern torch versions.

**Comment by jeffra** [comment]
@skiingpacman please give #2274 a try, this should fix your issue.

**Comment by skiingpacman** [comment]
@jeffra - just checked with current Master (088212a7) and can confirm that the issue is resolved.
Many thanks for fixing this.
