### ISSUE TITLE
Why Stage2 need communicate gradients every steps, even if grad_accumulation_steps > 1 ?

### ISSUE THREAD

**Issue by woolpeeker** [microsoft/DeepSpeed#2252]
Under ZeRO-stage-2
I check the code and use torch profiler, I found in every steps the gradient will be reduced whether it is on grad accumulation boundary.
Is there any reason to do it?
I think it might be uneccessary to communicate grad in every steps.

**Comment by tjruwase** [comment]
@woolpeeker, thanks for the question. For zero stage 2 (and 3), gradient reduction is required after every backward because of gradient partitioning. Each rank retains only the accumulated gradients of its partition and discards the rest to save memory. So, we cannot wait till grad accumulation boundary for reduction.

**Comment by woolpeeker** [comment]
Got it. Thanks for replying.
