### ISSUE TITLE
load_optimizer_states not obeyed in _load_zero_checkpoint

### ISSUE THREAD

**Issue by corbyrosset** [microsoft/DeepSpeed#227]
As I brought up before in meetings, deepspeed_light.py > _load_zero_checkpoint line 1136 does not obey the input argument of "load_optimizer_states". An extra if statement is needed such that:

```
if load_optimizer_states:
    self.optimizer.load_state_dict(zero_sd['optimizer_state_dict'],
                                       load_optimizer_states=load_optimizer_states)
```

original function:

```
def _load_zero_checkpoint(self, load_dir, tag, load_optimizer_states=True):
        zero_checkpoint_name = self._get_zero_ckpt_name(load_dir, tag)
        if not os.path.exists(zero_checkpoint_name):
            logging.warn(
                'Client provided checkpoint load path: {} does not exist ... skip checkpoint load'
                .format(zero_checkpoint_name))
            return None

        zero_sd = torch.load(zero_checkpoint_name, map_location='cpu')
        self.optimizer.load_state_dict(zero_sd['optimizer_state_dict'],
                                       load_optimizer_states=load_optimizer_states)
```

Thanks, Corby :)

**Comment by tjruwase** [comment]
@corbyrosset  Thanks for this report. However, I don't think there is a problem with the code, but rather there is some confusion because of the overloading of "optimizer". Specifically, `load_optimizer_states`  refers to the base (fp32) optimizer like Adam/Lamb, etc., while `self.optimizer` in this context refers to ZeRO, a wrapper (fp16) optimizer. And so setting `load_optimizer_states ` is not to disable loading on ZeRO states, but rather of the underlying Adam optimizer states, as seen [here](https://github.com/microsoft/DeepSpeed/blob/b466e84e9fb9172a7677ed4ba1c70865d2a8f222/deepspeed/pt/deepspeed_zero_optimizer.py#L1346-L1347). 

Does that clear up your concern?
