### ISSUE TITLE
[BUG] Inference return wrong results when the input length is bigger than 1024

### ISSUE THREAD

**Issue by yingapple** [microsoft/DeepSpeed#2485]
**Describe the bug**
I use a prompt whose length is longer than 1024. 
Then the deepspped return wrong result.

**To Reproduce**
1. Initialize OPT model use policy injection.
2. just use a prompt whose length longer than 1024.

**Expected behavior**

**ds_report output**
![img_v2_6bd4592d-93bb-4e47-a2a4-3bed8d1b649g](https://user-images.githubusercontent.com/4669452/200474424-0d09b649-c21c-4fcb-8f3a-4be24e797a3d.jpg)

**Screenshots**
![img_v2_fabbaede-6d0b-479b-8fd6-aa431c25f0dg](https://user-images.githubusercontent.com/4669452/200473967-4937ead5-95e9-4b2e-a4d4-418d15abb30e.jpg)

**System info**
 - GPU: 1  v100.
 - Deepspeed-MII: the latest version.
 - Cuda Version: 11.4
 - Python version 3.7.14

**Comment by cmikeh2** [comment]
Hi @yingapple,

Thanks for reporting this. I was able to reproduce the issue you reported. The root cause of this issue is a recently added argument to `init_inference` to control how much memory should be allocated ahead of time for the KV-cache. Internally this value defaults to 1024 if no explicit argument is supplied, likely leading to the issue that you're seeing. For an 1174-token input, by setting the `max_tokens` argument in `init_inference` to 2048 I was able to resolve this issue in my environment. Can you try supplying a larger value to `init_inference` to see if that provides accurate results?

**Comment by yingapple** [comment]
> Hi @yingapple,
> 
> Thanks for reporting this. I was able to reproduce the issue you reported. The root cause of this issue is a recently added argument to `init_inference` to control how much memory should be allocated ahead of time for the KV-cache. Internally this value defaults to 1024 if no explicit argument is supplied, likely leading to the issue that you're seeing. For an 1174-token input, by setting the `max_tokens` argument in `init_inference` to 2048 I was able to resolve this issue in my environment. Can you try supplying a larger value to `init_inference` to see if that provides accurate results?

Thanks, everything goes well by following your advice. I'll close this issue.
