### ISSUE TITLE
Failing to compile from install.sh

### ISSUE THREAD

**Issue by tbennun** [microsoft/DeepSpeed#251]
I'm getting the following two errors while compiling the code:

1.
```
csrc/lamb/fused_lamb_cuda_kernel.cu:58:10: fatal error: type_shim.h: No such file or directory
 #include "type_shim.h"
          ^~~~~~~~~~~~~
compilation terminated.
```
I copied two files from `thirdparty/apex/csrc` (`compat.h` and `type_shim.h`) and it worked.

2.
```
csrc/transformer/general_kernels.cu:1:10: fatal error: general_kernels.h: No such file or directory
 #include "general_kernels.h"
```
It seems that (for some reason) the `-I` flag is not using absolute paths, but the compiled files are. I fixed that by adding absolute paths in `setup.py`, replacing all relevant `include_dirs` lines with:
```python
include_dirs=[os.path.join(os.path.abspath(os.path.dirname(__file__)), 'csrc', 'includes')],
```

I can also upload a pull request if that works better.

**Comment by tjruwase** [comment]
@tbennun  Thanks for your interest in DeepSpeed. 
It seems both errors have the same root cause, which is that `include_dirs` [directive ](https://github.com/microsoft/DeepSpeed/blob/fd2a8fd5b25b293252063aa2bb5a1047b146749e/setup.py#L97) is not working for some reason in your setup. I don't think we should need absolute path if you are running from the deepspeed installation folder. 

Here are a couple of questions:
1) Does your solution 2 address error 1?
2) Did you run install.sh from the deepspeed folder, and how did you run it?

**Comment by tbennun** [comment]
1. Indeed, the `include_dirs` fix also fixed the first error.
2. I use Anaconda Python to set up an environment, as docker is currently not supported on our environment. I cloned the repo recursively, went into the main folder and ran install.sh without arguments. My exact process is as follows:
* `conda create -n deepspeed python=3.7; conda activate deepspeed`
* `git clone --recursive https://github.com/microsoft/DeepSpeed.git`
* `cd DeepSpeed`
* `./install.sh`

**Comment by vfdev-5** [comment]
Same issue for me with relative path of `include_dirs` when executing `install.sh` like that:
```
cd /tmp/DeepSpeed && ./install.sh -d -r
```

**Comment by tjruwase** [comment]
@tbennun  and @vfdev-5 Are you still having this issue?

**Comment by tbennun** [comment]
I can confirm this issue has been resolved for me on the latest master. Thanks!

**Comment by tbennun** [comment]
@vfdev-5 if it's still not working for you I'll reopen.
