### ISSUE TITLE
[BUG] inference BLOOM model with checkpoint.json

### ISSUE THREAD

**Issue by chaoyujiang** [microsoft/DeepSpeed#2557]
**Describe the bug**
Hit an error:  
at deeepspeed/inference/engine.py , line 412, in _load_checkpoint
AttributeError: 'dict' object has no attribute 'load'

**To Reproduce**
cd DeepSpeedExamples-master/inference/huggingface/text-generation

deepspeed --num_gpus 2 ./inference-test.py  --use_meta_tensor=True

![image](https://user-images.githubusercontent.com/35489248/204699455-ffdc146f-ef4e-4531-88d7-737c9cf93fdb.png)
**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.
![image](https://user-images.githubusercontent.com/35489248/204699560-231ac5d4-8b5d-43a7-9b60-07cd7526671f.png)

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**
#https://github.com/microsoft/DeepSpeedExamples/issues/224#issue-1468983124

**Comment by lekurile** [comment]
Hi @chaoyujiang,

I see that your command in the DeepSpeedExamples [issue](https://github.com/microsoft/DeepSpeedExamples/issues/224#issue-1468983124) is:
<pre>
deepspeed --num_gpus 2 ./inference-test.py --name ./microsoft/bloom-deepspeed-inference-int8/ --use_meta_tensor=True
</pre>
To properly access the model in HuggingFace the name argument should be formatted as follows:
<pre>
--name microsoft/bloom-deepspeed-inference-int8
</pre>
without the initial `./` and `/` at the end.

Aside from that, the `microsoft/bloom-deepspeed-inference-int8` model is a presharded model targeting 8 A100 GPUs

https://huggingface.co/microsoft/bloom-deepspeed-inference-int8

"This is a custom INT8 version of the original [BLOOM weights](https://huggingface.co/bigscience/bloom) to make it fast to use with the [DeepSpeed-Inference](https://www.deepspeed.ai/tutorials/inference-tutorial/) engine which uses Tensor Parallelism. In this repo the tensors are split into 8 shards to target 8 GPUs."

In both commands specified in this issue and the DeepSpeedExamples issue, I see that `--num_gpus 2`, which will not work with this model.

Can you please try running with `--num_gpus 8` and fixing the `--name` argument supplied to the command?

Thanks,
Lev

**Comment by chaoyujiang** [comment]
> Hi @chaoyujiang,
> 
> I see that your command in the DeepSpeedExamples [issue](https://github.com/microsoft/DeepSpeedExamples/issues/224#issue-1468983124) is:
> 
> deepspeed --num_gpus 2 ./inference-test.py --name ./microsoft/bloom-deepspeed-inference-int8/ --use_meta_tensor=True
> To properly access the model in HuggingFace the name argument should be formatted as follows:
> 
> --name microsoft/bloom-deepspeed-inference-int8
> without the initial `./` and `/` at the end.
> 
> Aside from that, the `microsoft/bloom-deepspeed-inference-int8` model is a presharded model targeting 8 A100 GPUs
> 
> https://huggingface.co/microsoft/bloom-deepspeed-inference-int8
> 
> "This is a custom INT8 version of the original [BLOOM weights](https://huggingface.co/bigscience/bloom) to make it fast to use with the [DeepSpeed-Inference](https://www.deepspeed.ai/tutorials/inference-tutorial/) engine which uses Tensor Parallelism. In this repo the tensors are split into 8 shards to target 8 GPUs."
> 
> In both commands specified in this issue and the DeepSpeedExamples issue, I see that `--num_gpus 2`, which will not work with this model.
> 
> Can you please try running with `--num_gpus 8` and fixing the `--name` argument supplied to the command?
> 
> Thanks, Lev

Thanks for your reply. I download the model "microsoft/bloom-deepspeed-inference-int8" in local disk, So I appoint the path of the model. Another question you're rigth, the num_gpus should be 8.

**Comment by lekurile** [comment]
Another thing to consider, currently the `DS_Pipeline` class has an internal list enumerating the presharded Microsoft huggingface models:
https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/utils.py#L38

If the `model_name` matches an item in the list, the `checkpoints_json` return value will be set to the existing `ds_inference_config.json` config file:
https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/utils.py#L74

If the `model_name` isn't in the list, we create our own `checkpoints.json` config file:
https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/utils.py#L78

I think potentially the issue here is, you have a local download of the `microsoft/bloom-deepspeed-inference-int8`, but since your name is supplied as `./microsoft/bloom-deepspeed-inference-int8/`, you end up taking the `else` code path in `_generate_json` since it won't match an item in the `self.tp_presharded_models` list:
https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/utils.py#L75

Could you try making sure that your `self.checkpoints_json` in the `DS_Pipeline` points to your local `ds_inference_config.json`?
https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/utils.py#L46

**Comment by chaoyujiang** [comment]
> ch an item in the

Yes, I make a little adjustment about utils.py. 
![util py](https://user-images.githubusercontent.com/35489248/205531812-20b84e49-202b-485c-a50f-7e2a8609afb5.jpg)
The param checkpoint and base_dir of API init_inference are "/mnt/models/microsoft/bloom-deepspeed-inference-int/ds_inference_config.json" , "/mnt/models/microsoft/bloom-deepspeed-inference-int/"

**Comment by lekurile** [comment]
Hi @chaoyujiang,

From the error message above, you hit the `_load_checkpoint` path in the InferenceEngine `__init__`. That path will only be taken if this [condition](https://github.com/microsoft/DeepSpeed/blob/v0.7.6/deepspeed/inference/engine.py#L88) is true:
<pre>
if config.checkpoint and not config.replace_with_kernel_inject:
    self._load_checkpoint(config.checkpoint)
</pre>
In the latest [inference-test.py example](https://github.com/microsoft/DeepSpeedExamples/blob/d5eb762eec7c8efa9cc555b03caaf84869204463/inference/huggingface/text-generation/inference-test.py#L41), `replace_with_kernel_inject=True` when the init_inference API is called, so it shouldn't take the `_load_checkpoint` path above.

I'm curious if you made any changes in `inference-test.py`, specifically the input arguments to the init_inference API.

Could you please try pulling the latest from master in the `DeepSpeedExamples` repository and running agian?

Thanks,
Lev

**Comment by jeffra** [comment]
@chaoyujiang, please re-open if you're still having an issue.
