### ISSUE TITLE
Too many global variables

### ISSUE THREAD

**Issue by chunyang-wen** [microsoft/DeepSpeed#256]
There are lots of `global` usage in a couple of modules. Maybe we should try to reduce the usage and have a better structure of the code. For example, if a lot of functions share similar globals, we can make a class. In order to be compatible with the old code, we can create aliases for them.

**Comment by ShadenSmith** [comment]
Hi @chunyang-wen, totally agree that we should avoid global variable usage when it makes sense to do so. We always try to improve the codebase as time permits when we work on DeepSpeed. We also always love pull requests :-).

**Comment by chunyang-wen** [comment]
I am planning to update related code if I am available.

**Comment by lekurile** [comment]
Hi @chunyang-wen,

Thank you for submitting this issue. Closing the issue for now due to its age, but feel free to open another issue if you have suggestions for improving the code quality of DeepSpeed in its current state (lots of refactor and changes since when this issue was opened).

PRs are always appreciated!

Thanks,
Lev
