### ISSUE TITLE
[BUG]AttributeError: module 'deepspeed' has no attribute 'ops'

### ISSUE THREAD

**Issue by SiTu1O** [microsoft/DeepSpeed#2584]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by yaozhewei** [comment]
Could you give more details? We cannot clearly follow the "reproduce steps"

**Comment by jeffra** [comment]
I was able to reproduce what I think the issue is but it only seems to happen on python 3.6. It appears this regression was introduced since v0.7.5 release. I am bisecting further now and will push a fix soon.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/645595/206585702-761cedb2-1082-422b-9fc0-ad6409b10b7e.png">

**Comment by jeffra** [comment]
@SiTu1O, this should be resolved now. Please re-open if you still see the issue.
