### ISSUE TITLE
Installation on Windows 10 (Deepspeed inference)

### ISSUE THREAD

**Issue by Eichhof** [microsoft/DeepSpeed#2588]
Hello

I'm running Windows 10 and I would like to install DeepSpeed to speed up inference of GPT-J. My system is the following:

```
Windows 10
cuda 11.6
torch 1.13.0
Python 3.9.12
```

When running the following command in Powershell to build the wheel

```
$env:DS_BUILD_OPS = 0
python setup.py bdist_wheel
```

I'm getting the following error (same when running pip install deepspeed):

```
DS_BUILD_OPS=0
←[93m [WARNING] ←[0m please install triton==1.0.0 if you want to use sparse attention
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
←[93m [WARNING] ←[0m async_io requires the dev libaio .so object and headers but these were not found.
←[93m [WARNING] ←[0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
Install Ops={'cpu_adam': False, 'cpu_adagrad': False, 'fused_adam': False, 'fused_lamb': False, 'sparse_attn': False, 'transformer': False, 'stochastic_transformer': False, 'async_io': False, 'utils': False, 'quantizer': False, 'transformer_inference': False, 'spatial_inference': False}
Traceback (most recent call last):
  File "C:\Users\myUsername\Desktop\DeepSpeed\setup.py", line 196, in <module>
    create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
  File "C:\Users\myUsername\Desktop\DeepSpeed\setup.py", line 190, in create_dir_symlink
    os.symlink(src, dest)
OSError: [WinError 1314] A required privilege is not held by the client: '..\\..\\csrc' -> '.\\deepspeed\\ops\\csrc'
```

Can somebody help me getting inference with DeepSpeed running on Windows?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @Eichhof,

Can you please confirm if you are running this in administrative mode?

Thanks,
Reza

**Comment by Eichhof** [comment]
Thank you very much. In administrator mode I could now build the wheel. I then installed the wheel using pip. The problem now is that when calling `deepspeed.init_inference(...)`, I'm getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\myUsername\\Anaconda3\\envs\\huggingface\\lib\\site-packages\\deepspeed\\ops\\csrc/transformer/inference/csrc/pt_binding.cpp'

**Comment by Eichhof** [comment]
Any help on this? I could not find a solution.

**Comment by genbs** [comment]
Same problem

**Comment by Eichhof** [comment]
Was somebody able to get Deepseed running for inference on Windows 10?

**Comment by marcoseduardopm** [comment]
After trying forever, I got it working. That's what I have done:
- Install the vs build tool 2019. If you already have it installed, repair it;
- Install Miniconda (if you haven't it already);
- Open "Anaconda Prompt (MiniConda3)";
- Create a python 3.10 env using: "conda create -n dsenv python=3.10.6"
- Activate the conda env using "conda activate dsenv";
- Install Pytorch and CUDA using: "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia";
- Close anaconda prompt;
- Open the Start -> "x64 Native Tools Command Prompt for VS 2019";
- Initialize conda on the Command prompt using "conda init cmd.exe";
- Reopen the  "x64 Native Tools Command Prompt for VS 2019" AS AN **ADMINISTRATOR**;
- Activate the conda env using "conda activate dsenv";
- Go to your root folder (could be c:\ or any other) and clone que DeepSpeed project "git clone https://github.com/microsoft/DeepSpeed";
- Depending on the fixes of the DeepSpeed repository, this step might or not be needed: Download here this file (https://drive.google.com/drive/folders/11EYHosWfDLrrVbniBLV1j82qeurpGlvX?usp=sharing) and replace the file at DeepSpeed\csrc\transformer\inference\csrc\pt_binding.cpp (see comments below);
- Go to the deepspeed folder using "cd DeepSpeed";
- Make 10 prayers to your god and try to install using "build_win.bat";
- A .whl will be created in the dist folder.


Extra Notes: 
Note: Tytorch version 1.13.1 with CUDA 11.7 also worked for me, but since it is an older version, I did not mention it in the steps above. If you need that version, install using "conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia"


About the replacement of file pt_binding.cpp: all I did was change lines  531, 532, 539, and 540:
New Lines 531 and 532:
                                     {static_cast<unsigned>(hidden_dim * Context::Instance().GetMaxTokenLenght()),
                                      static_cast<unsigned>(k * Context::Instance().GetMaxTokenLenght()),

New lines 539 and 540:
                                       {static_cast<unsigned>(hidden_dim * Context::Instance().GetMaxTokenLenght()),
                                        static_cast<unsigned>(k * Context::Instance().GetMaxTokenLenght()),


**For anyone that just want the final .whl to install using python, here it is (no prayers needed):** 
https://drive.google.com/drive/folders/117GSNHcJyzvMPTftl0aPBSwQVsU-z4bM?usp=sharing

**Comment by marcoseduardopm** [comment]
> > (Note: these steps are for the interference only mode) After trying forever, I got it working. That's what I have done:
> > 
> > * Install the vs build tool 2019. If you already have it installed, repair it;
> > * Install Miniconda (if you haven't it already);
> > * Install CUDA 11.7 from https://developer.nvidia.com/cuda-11-7-0-download-archive ;
> > * Open "Anaconda Prompt (MiniConda3)";
> > * Create a python 3.10 env using: "conda create -n dsenv python=3.10.6"
> > * Activate the conda env using "conda activate dsenv";
> > * Install Pytorch and CUDA using: "conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia";
> > * Close anaconda prompt;
> > * Open the Start -> "x64 Native Tools Command Prompt for VS 2019";
> > * Initialize conda on the Command prompt using "conda init cmd.exe";
> > * Reopen the  "x64 Native Tools Command Prompt for VS 2019" AS AN **ADMINISTRATOR**;
> > * Activate the conda env using "conda activate dsenv";
> > * Go to your root folder (could be c:\ or any other) and clone que DeepSpeed project "git clone https://github.com/microsoft/DeepSpeed";
> > * Depending on the fixes of the DeepSpeed repository, this step might or not be needed: Download here this file (https://drive.google.com/drive/folders/11EYHosWfDLrrVbniBLV1j82qeurpGlvX?usp=sharing) and replace the file at DeepSpeed\csrc\transformer\inference\csrc\pt_binding.cpp (see comments below);
> > * Go to the deepspeed folder using "cd DeepSpeed";
> > * Make 10 prayers to your god and try to install using "build_win.bat";
> > * A .whl will be created in the dist folder.
> > 
> > To install the generated .whl, just use: For Python 3.10 version: pip install deepspeed-0.8.3+6eca037c-cp310-cp310-win_amd64.whl For Pytohn 3.9 version: pip install deepspeed-0.8.3+4d27225f-cp39-cp39-win_amd64.whl
> > Extra Notes: Note: Tytorch version 1.13.1 with CUDA 11.7 also worked for me, but since it is an older version, I did not mention it in the steps above. If you need that version, install using "conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia"
> > About the replacement of file pt_binding.cpp: all I did was change lines 531, 532, 539, and 540: New Lines 531 and 532: {static_cast(hidden_dim * Context::Instance().GetMaxTokenLenght()), static_cast(k * Context::Instance().GetMaxTokenLenght()),
> > New lines 539 and 540: {static_cast(hidden_dim * Context::Instance().GetMaxTokenLenght()), static_cast(k * Context::Instance().GetMaxTokenLenght()),
> > **For anyone that just want the final .whl to install using python, here it is (no prayers needed):** https://drive.google.com/drive/folders/117GSNHcJyzvMPTftl0aPBSwQVsU-z4bM?usp=sharing
> 
> aslo report "LINK : fatal error LNK1181: cannot open input file 'aio.lib'" but use ur whl file as well ,thanks!


Did you use build_win.bat to build so that DS_BUILD_AIO is set to 0?

**Comment by AngelTs** [comment]
> (Note: these steps are for the interference only mode) After trying forever, I got it working. That's what I have done:
> 
> ...
> About the replacement of file pt_binding.cpp: all I did was change lines 531, 532, 539, and 540: New Lines 531 and 532: {static_cast(hidden_dim * Context::Instance().GetMaxTokenLenght()), static_cast(k * Context::Instance().GetMaxTokenLenght()),
> 
> New lines 539 and 540: {static_cast(hidden_dim * Context::Instance().GetMaxTokenLenght()), static_cast(k * Context::Instance().GetMaxTokenLenght()),
> 
> ...
These sentences have at least four errors- Not "Context::Instance()", but "InferenceContext::Instance()" and still can't compile, because must use <> after static_cast

**Comment by loadams** [comment]
This should be resolved with our latest Windows whl - please check the blog post and open a new issue if you are still hitting this.
