### ISSUE TITLE
SSH-less connection on Kubernetes

### ISSUE THREAD

**Issue by dogacancolak** [microsoft/DeepSpeed#2679]
**Is your feature request related to a problem? Please describe.**
What is the advised way to run DeepSpeed on Kubernetes? Starting an ssh daemon does not sound optimal, since we would need to have two processes per container: one for deepspeed and one for ssh.

Using MPI isn't a solution either since MPI also uses ssh to establish the connection.

**Comment by hjp709394** [comment]
What's the status of this item?

**Comment by dogacancolak** [comment]
I ended up with two methods of running a multi-node task. The first method is indeed setting up password-less SSH connections between the pods and just using the deepspeed launcher with the hostfile listing SSH hostnames.

The other way is using the torchrun command. If you use this one, you need to call `torch.distributed.init_distributed` instead of `deepspeed.initialize` in the training script. Also, unlike the deepspeed launcher, this command needs to be run independently on all pods, and you must pass the address of one of the pods to act as the master node.

**Comment by jungyh0218** [comment]
This issue is already closed but I want to share the detailed method I used to deal with this issue.

**Using torchrun instead of deepspeed launcher**
As far as I know, using deepspeed launcher is not mandatory for using deepspeed configuration. As @dogacancolak mentioned, I also tried using torchrun launcher. Following is how to modify your code;
```
#switch deepspeed method to torch.distributed method.
#deepspeed.init_distributed() 
torch.distributed.init_process_group(backend='nccl')
```
And run the code with torchrun launcher. Since torchrun launcher does not invoke worker nodes via pdsh, it is necessary to run the code independently on all pods. Using MPIJob or PyTorchJob of [Kubeflow](https://github.com/kubeflow/) can do this automatically.

**Setting passwordless SSH in kubernetes pods**
To set passwordless SSH in kubernetes, open-ssh and pdsh have to be installed in Docker image. I created a Dockerfile based on NGC Pytorch image.
https://gist.github.com/jungyh0218/c04a285aadaa1efe3df289a61cf77f74

To use passwordless SSH, create ssh keys.
```
ssh-keygen -t rsa
cp id_rsa.pub authorized_keys
``` 
To pass these key files, use kubernetes secret. 
```
kubectl create secret generic my-ssh-key --from-file=path/to/id_rsa --from-file=path/to/id_rsa.pub --from-file=path/to/authorized_keys
```
After creating the secret, deploy your kubernetes deployment and mount the secret volume. When creating pods, you have to make it sure that open-sshd service is running. You also need to copy id_rsa and authorized_keys in /root/.ssh folder. Do these tasks in your init container or container commands.

If someone has any other better idea, share it please. :)

**Comment by divisionblur** [comment]
> This issue is already closed but I want to share the detailed method I used to deal with this issue.这个问题已经结束了，但我想分享一下我用来处理这个问题的详细方法。
> 
> **Using torchrun instead of deepspeed launcher使用 torchrun 代替 deepspeed 启动器** As far as I know, using deepspeed launcher is not mandatory for using deepspeed configuration. As @dogacancolak mentioned, I also tried using torchrun launcher. Following is how to modify your code;据我所知，使用 Deepspeed 配置并不强制要求使用 DeepSpeed 启动器。正如@dogacancolak 提到的，我还尝试使用 torchrun 启动器。以下是如何修改您的代码；
> 
> ```
> #switch deepspeed method to torch.distributed method.
> #deepspeed.init_distributed() 
> torch.distributed.init_process_group(backend='nccl')
> ```
> 
> And run the code with torchrun launcher. Since torchrun launcher does not invoke worker nodes via pdsh, it is necessary to run the code independently on all pods. Using MPIJob or PyTorchJob of [Kubeflow](https://github.com/kubeflow/) can do this automatically.并使用 torchrun 启动器运行代码。由于torchrun启动器不通过pdsh调用工作节点，因此有必要在所有pod上独立运行代码。使用 Kubeflow 的 MPIJob 或 PyTorchJob 可以自动完成此操作。
> 
> **Setting passwordless SSH in kubernetes pods在 kubernetes pod 中设置无密码 SSH** To set passwordless SSH in kubernetes, open-ssh and pdsh have to be installed in Docker image. I created a Dockerfile based on NGC Pytorch image.要在 kubernetes 中设置无密码 SSH，必须在 Docker 镜像中安装 open-ssh 和 pdsh。我创建了一个基于 NGC Pytorch 镜像的 Dockerfile。 https://gist.github.com/jungyh0218/c04a285aadaa1efe3df289a61cf77f74
> 
> To use passwordless SSH, create ssh keys.要使用无密码 SSH，请创建 ssh 密钥。
> 
> ```
> ssh-keygen -t rsa
> cp id_rsa.pub authorized_keys
> ```
> 
> To pass these key files, use kubernetes secret.要传递这些密钥文件，请使用 kubernetes Secret。
> 
> ```
> kubectl create secret generic my-ssh-key --from-file=path/to/id_rsa --from-file=path/to/id_rsa.pub --from-file=path/to/authorized_keys
> ```
> 
> After creating the secret, deploy your kubernetes deployment and mount the secret volume. When creating pods, you have to make it sure that open-sshd service is running. You also need to copy id_rsa and authorized_keys in /root/.ssh folder. Do these tasks in your init container or container commands.创建密钥后，部署 kubernetes 部署并挂载密钥卷。创建 pod 时，必须确保 open-sshd 服务正在运行。您还需要将 id_rsa 和authorized_keys 复制到/root/.ssh 文件夹中。在 init 容器或容器命令中执行这些任务。
> 
> If someone has any other better idea, share it please. :)

请问能给个示例吗？不太熟悉k8s，怎么相互拷贝公钥呢？

**Comment by dogacancolak** [comment]
https://github.com/microsoft/DeepSpeed/pull/5728
this PR eliminates the need for SSH, essentially the launching mechanism is now identical to `torchrun` when the `--no-ssh` flag is used, you can directly use the deepspeed launcher without setting up password-less SSH :)

**Comment by NicoZenith** [comment]
@dogacancolak Thanks for this PR!
So this way we should just call deepspeed with the `srun` command? or should we build a hostfile with the nodes name? A quick demo on how to use deepspeed with multinodes in your setting would be amazing! 
Thanks

**Comment by dogacancolak** [comment]
Hi @NicoZenith, sorry for the late response. Just created another PR to add documentation on using the new mode: https://github.com/microsoft/DeepSpeed/pull/6455
