### ISSUE TITLE
[Question] Why type is BLOOM in checkpoints.json?

### ISSUE THREAD

**Issue by sindhuvahinis** [microsoft/DeepSpeed#2910]
I understand that DeepSpeed introduced sharded checkpoints feature for BLOOM first. But now, to load the model from HF through meta tensors, for any model, type seems to enforced to enter as 'BLOOM'. 

But when the sharded checkpoints is generated, the generated ds_inference_config.json has type as 'ds_model'. 

Will the new type for each model be introduced in the future?

**Comment by mrwyattii** [comment]
The sharded checkpoint loading developed for BLOOM has been generalized to more models (GPT-J, GPT-NEOX, and OPT). See #2547 for more on that.

Since then, checkpoints with type `BLOOM` or `DS_MODEL` will follow the same path for loading:
https://github.com/microsoft/DeepSpeed/blob/dc01cee5cab07562bb48740b112f5cb23a90877c/deepspeed/runtime/state_dict_factory.py#L34
