### ISSUE TITLE
[QUESTION] BLOOM not supported by AutoTP

### ISSUE THREAD

**Issue by delock** [microsoft/DeepSpeed#2915]
Hi @molly-smith, we are recently enabling LLM on CPU and want to use AutoTP to reduce latency of LLM inference.   From our experiment, AutoTP can work with GPT-J 6B inference well, but does not support BLOOM-176B.   Can I ask the reason that AutoTP cannot support BLOOM?   Is it because of unique model architecture of BLOOM or due to other reason?   Do you plan to support more models i.e. BLOOM in AutoTP?

Appreciate if I can get a brief answer from you.  We used AutoTP for GPT-J and its very helpful.   We wonder whether we can do the same for BLOOM, or whether we need to implement kernel injection path in order to use tensor parallel for BLOOM.  Any insight on this will be very helpful to us.  Thanks!

**Comment by RezaYazdaniAminabadi** [comment]
Hi @delock, 

May I ask why you cannot use this with kernel-inject=True and not the AutoTP?
Thanks,
Reza

**Comment by molly-smith** [comment]
Closing as question is answered in linked discussion.

**Comment by starlitsky2010** [comment]
I also met this problem.
According to the web: 
https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/#supported-models

DeepSpeed now supports automatic tensor parallelism for HuggingFace models by default as long as kernel injection is not enabled and an injection policy is not provided. This allows our users to improve performance of models that are not currently supported via kernel injection, without providing the injection policy.

Bloom is in the supported models list.

But I've met the following error:
AssertionError: AutoTP not supported for model. Please use kernel injection since container policy for model exists.

Could you provide some tips about this error?

Detail logs:
[2023-05-30 15:41:12,649] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/user/InferenceEngine/DeepSpeedExamples/inference/huggingface/bloomz/test_bloomz.py:28 │
│ in <module>                                                                                      │
│                                                                                                  │
│    25 # https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/#supported-models        │
│    26 # DeepSpeed now supports automatic tensor parallelism for HuggingFace models by default    │
│    27 # as long as kernel injection is not enabled and an injection policy is not provided.      │
│ ❱  28 generator.model = deepspeed.init_inference(generator.model,                                │
│    29 │   │   │   │   │   │   │   │   │   │      mp_size=world_size,                             │
│    30 │   │   │   │   │   │   │   │   │   │      dtype=torch.half)                               │
│    31                                                                                            │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ __init__.py:311 in init_inference                                                                │
│                                                                                                  │
│   308 │                                                                                          │
│   309 │   ds_inference_config = DeepSpeedInferenceConfig(**config_dict)                          │
│   310 │                                                                                          │
│ ❱ 311 │   engine = InferenceEngine(model, config=ds_inference_config)                            │
│   312 │                                                                                          │
│   313 │   return engine                                                                          │
│   314                                                                                            │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ inference/engine.py:139 in __init__                                                              │
│                                                                                                  │
│   136 │   │   │   │   self._apply_injection_policy(config)                                       │
│   137 │   │   │   else:                                                                          │
│   138 │   │   │   │   # 3. Automatic Tensor Parallelism                                          │
│ ❱ 139 │   │   │   │   parser_dict = AutoTP.tp_parser(model)                                      │
│   140 │   │   │   │   print("AutoTP: ", parser_dict)                                             │
│   141 │   │   │   │   for client_module, injection_policy in parser_dict:                        │
│   142 │   │   │   │   │   if isinstance(injection_policy, str):                                  │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ module_inject/auto_tp.py:99 in tp_parser                                                         │
│                                                                                                  │
│    96 │   │   gem_list = []                                                                      │
│    97 │   │                                                                                      │
│    98 │   │   module_list = AutoTP.get_module_list(model)                                        │
│ ❱  99 │   │   assert AutoTP.supported(model), "AutoTP not supported for model. Please use kern   │
│   100 │   │   if AutoTP.kernel_supported(module_list) else "AutoTP not supported for model. Pl   │
│   101 │   │   for module in module_list:                                                         │
│   102 │   │   │   for key, submodule in module._modules.items():                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: AutoTP not supported for model. Please use kernel injection since container policy for model exists.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/user/InferenceEngine/DeepSpeedExamples/inference/huggingface/bloomz/test_bloomz.py:28 │
│ in <module>                                                                                      │
│                                                                                                  │
│    25 # https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/#supported-models        │
│    26 # DeepSpeed now supports automatic tensor parallelism for HuggingFace models by default    │
│    27 # as long as kernel injection is not enabled and an injection policy is not provided.      │
│ ❱  28 generator.model = deepspeed.init_inference(generator.model,                                │
│    29 │   │   │   │   │   │   │   │   │   │      mp_size=world_size,                             │
│    30 │   │   │   │   │   │   │   │   │   │      dtype=torch.half)                               │
│    31                                                                                            │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ __init__.py:311 in init_inference                                                                │
│                                                                                                  │
│   308 │                                                                                          │
│   309 │   ds_inference_config = DeepSpeedInferenceConfig(**config_dict)                          │
│   310 │                                                                                          │
│ ❱ 311 │   engine = InferenceEngine(model, config=ds_inference_config)                            │
│   312 │                                                                                          │
│   313 │   return engine                                                                          │
│   314                                                                                            │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ inference/engine.py:139 in __init__                                                              │
│                                                                                                  │
│   136 │   │   │   │   self._apply_injection_policy(config)                                       │
│   137 │   │   │   else:                                                                          │
│   138 │   │   │   │   # 3. Automatic Tensor Parallelism                                          │
│ ❱ 139 │   │   │   │   parser_dict = AutoTP.tp_parser(model)                                      │
│   140 │   │   │   │   print("AutoTP: ", parser_dict)                                             │
│   141 │   │   │   │   for client_module, injection_policy in parser_dict:                        │
│   142 │   │   │   │   │   if isinstance(injection_policy, str):                                  │
│                                                                                                  │
│ /home/user/anaconda3/envs/user-3.10-torch2.0-cu117/lib/python3.10/site-packages/deepspeed/ │
│ module_inject/auto_tp.py:99 in tp_parser                                                         │
│                                                                                                  │
│    96 │   │   gem_list = []                                                                      │
│    97 │   │                                                                                      │
│    98 │   │   module_list = AutoTP.get_module_list(model)                                        │
│ ❱  99 │   │   assert AutoTP.supported(model), "AutoTP not supported for model. Please use kern   │
│   100 │   │   if AutoTP.kernel_supported(module_list) else "AutoTP not supported for model. Pl   │
│   101 │   │   for module in module_list:                                                         │
│   102 │   │   │   for key, submodule in module._modules.items():                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: AutoTP not supported for model. Please use kernel injection since container policy for model exists.
[2023-05-30 15:41:14,045] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 989752
[2023-05-30 15:41:14,071] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 989753
[2023-05-30 15:41:14,072] [ERROR] [launch.py:324:sigkill_handler] ['/home/user/anaconda3/envs/user-3.10-torch2.0-cu117/bin/python', '-u', 'test_bloomz.py', '--local_rank=1'] exits with return code = 1
