### ISSUE TITLE
training.log[BUG]

### ISSUE THREAD

**Issue by haoyu-lab** [microsoft/DeepSpeed#3240]
Displayed in the training.log file
/Users/houhaoyu/Desktop/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/training_scripts/single_gpu/run_1.3b.sh: line 18: deepspeed: command not found

**Comment by hemangjoshi37a** [comment]
Here are some steps to resolve this issue:

1. Check if DeepSpeed is installed: Run `pip list` or `pip freeze` in your terminal to see if DeepSpeed is installed in your current Python environment. If DeepSpeed is not listed, install it using `pip install deepspeed`.

2. Find the DeepSpeed executable: If DeepSpeed is installed, locate the DeepSpeed executable by running `find $(dirname $(dirname $(which python)))/ -name deepspeed`. This command will search for the DeepSpeed executable within the Python environment's directories.

3. Add the DeepSpeed executable to the PATH: Once you've found the DeepSpeed executable, add its parent directory to your system's `PATH` variable. You can do this by running `export PATH=$PATH:/path/to/deepspeed/executable/parent/directory` in your terminal. Replace `/path/to/deepspeed/executable/parent/directory` with the actual path to the directory containing the DeepSpeed executable. To make this change permanent, add the same export command to your shell's startup script (e.g., ~/.bashrc, ~/.zshrc, or ~/.bash_profile).

4. Verify the DeepSpeed command is available: After adding the DeepSpeed executable to your PATH, run which deepspeed in the terminal. This command should now return the path to the DeepSpeed executable. If it still says "command not found," ensure that you've correctly updated the PATH variable and that the DeepSpeed executable is present in the specified directory.

5. Run the script again: After confirming that the DeepSpeed command is available in your terminal, try running the run_1.3b.sh script again.

If the issue persists after following these steps, consider providing more information in the GitHub issue, such as details about your operating system, Python environment, and any other relevant context. This will help the DeepSpeed maintainers in identifying the root cause and providing a more specific solution.

**Comment by haoyu-lab** [comment]
find $(dirname $(dirname $(which python)))/ -name deepspeed
The command cannot find the executable
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63897264/232213246-d6a772fb-beff-4bb3-bbdc-24be533a2e70.png">

**Comment by haoyu-lab** [comment]
> 以下是解决此问题的一些步骤：
> 
> 1. 检查是否安装了 DeepSpeed：在您的终端中运行`pip list`或`pip freeze`查看您当前的 Python 环境中是否安装了 DeepSpeed。如果未列出 DeepSpeed，请使用`pip install deepspeed`。
> 2. 查看DeepSpeed可执行文件：如果安装了DeepSpeed，请通过运行找到DeepSpeed可执行文件`find $(dirname $(dirname $(which python)))/ -name deepspeed`。此命令将在Python环境的目录中搜索DeepSpeed文件可执行文件。
> 3. 将深速可可文件到添加路：找到深速可可执行，将执行文件，将将父父目录添加到中中。。您您可以您可以可以通过通过在在在在终端终端终端运行中运行运行来`PATH`来执行`export PATH=$PATH:/path/to/deepspeed/executable/parent/directory`来执行`/path/to/deepspeed/executable/parent/directory`。要使这个更持久有效，请将相同的命令添加到您的shell的启动脚本（例如，~/.bashrc、~/.zshrc或~/.bash_profile）。
> 4. 验证深速命令：将深速可可可可文件的的后后后后后后后后后后后后后后的的的的后到您您的您的到到到您您的到终端终端终端终端终端在中终端终端终端终端终端运行终端中中运行运行运行运行运行运行运行中中中中运行运行运行运行运行运行运行运行运行运行运行运行您已经正确更新 PATH 变量并与 DeepSpeed 可执行文件存在于指定目录中。
> 5. 再次运行脚：确认 DeepSpeed 命令在您的最终中可用后，尝试再次运行 run_1.3b.sh 脚。
> 
> 在问题仍然仍然具体的解决方案。

find $(dirname $(dirname $(which python)))/ -name deepspeed
The command cannot find the executable
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63897264/232213246-d6a772fb-beff-4bb3-bbdc-24be533a2e70.png">

> Here are some steps to resolve this issue:
> 
> 1. Check if DeepSpeed is installed: Run `pip list` or `pip freeze` in your terminal to see if DeepSpeed is installed in your current Python environment. If DeepSpeed is not listed, install it using `pip install deepspeed`.
> 2. Find the DeepSpeed executable: If DeepSpeed is installed, locate the DeepSpeed executable by running `find $(dirname $(dirname $(which python)))/ -name deepspeed`. This command will search for the DeepSpeed executable within the Python environment's directories.
> 3. Add the DeepSpeed executable to the PATH: Once you've found the DeepSpeed executable, add its parent directory to your system's `PATH` variable. You can do this by running `export PATH=$PATH:/path/to/deepspeed/executable/parent/directory` in your terminal. Replace `/path/to/deepspeed/executable/parent/directory` with the actual path to the directory containing the DeepSpeed executable. To make this change permanent, add the same export command to your shell's startup script (e.g., ~/.bashrc, ~/.zshrc, or ~/.bash_profile).
> 4. Verify the DeepSpeed command is available: After adding the DeepSpeed executable to your PATH, run which deepspeed in the terminal. This command should now return the path to the DeepSpeed executable. If it still says "command not found," ensure that you've correctly updated the PATH variable and that the DeepSpeed executable is present in the specified directory.
> 5. Run the script again: After confirming that the DeepSpeed command is available in your terminal, try running the run_1.3b.sh script again.
> 
> If the issue persists after following these steps, consider providing more information in the GitHub issue, such as details about your operating system, Python environment, and any other relevant context. This will help the DeepSpeed maintainers in identifying the root cause and providing a more specific solution.

find $(dirname $(dirname $(which python)))/ -name deepspeed
The command cannot find the executable
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63897264/232213246-d6a772fb-beff-4bb3-bbdc-24be533a2e70.png">

**Comment by haoyu-lab** [comment]
> Here are some steps to resolve this issue:
> 
> 1. Check if DeepSpeed is installed: Run `pip list` or `pip freeze` in your terminal to see if DeepSpeed is installed in your current Python environment. If DeepSpeed is not listed, install it using `pip install deepspeed`.
> 2. Find the DeepSpeed executable: If DeepSpeed is installed, locate the DeepSpeed executable by running `find $(dirname $(dirname $(which python)))/ -name deepspeed`. This command will search for the DeepSpeed executable within the Python environment's directories.
> 3. Add the DeepSpeed executable to the PATH: Once you've found the DeepSpeed executable, add its parent directory to your system's `PATH` variable. You can do this by running `export PATH=$PATH:/path/to/deepspeed/executable/parent/directory` in your terminal. Replace `/path/to/deepspeed/executable/parent/directory` with the actual path to the directory containing the DeepSpeed executable. To make this change permanent, add the same export command to your shell's startup script (e.g., ~/.bashrc, ~/.zshrc, or ~/.bash_profile).
> 4. Verify the DeepSpeed command is available: After adding the DeepSpeed executable to your PATH, run which deepspeed in the terminal. This command should now return the path to the DeepSpeed executable. If it still says "command not found," ensure that you've correctly updated the PATH variable and that the DeepSpeed executable is present in the specified directory.
> 5. Run the script again: After confirming that the DeepSpeed command is available in your terminal, try running the run_1.3b.sh script again.
> 
> If the issue persists after following these steps, consider providing more information in the GitHub issue, such as details about your operating system, Python environment, and any other relevant context. This will help the DeepSpeed maintainers in identifying the root cause and providing a more specific solution.

find $(dirname $(dirname $(which python)))/ -name deepspeed
The command cannot find the executable
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63897264/232213246-d6a772fb-beff-4bb3-bbdc-24be533a2e70.png">

**Comment by mrwyattii** [comment]
@haoyu-lab if you run `which deepspeed`, do you see any output? How did you install deepspeed? Is this in a virtual environment?

**Comment by rguo12** [comment]
I got the same bug, pip list shows deepspeed but I cannot find the executable with 
find (dirname $(which python)))/ -name deepspeed

![Screenshot 2023-07-10 at 14 40 44](https://github.com/microsoft/DeepSpeed/assets/6904605/1d03e0ad-8ae4-43df-98c5-6042fa6c3844)
![Screenshot 2023-07-10 at 14 41 42](https://github.com/microsoft/DeepSpeed/assets/6904605/3c36cf6b-a247-4b66-a8ce-d0220d410f60)


Any tips for that?

**Comment by rguo12** [comment]
For my case, it does not work for Python 3.8, but works for Python 3.10.
