### ISSUE TITLE
[BUG] Does anybody reproduce a similar performance based on "Actor: OPT-1.3B, Reward: OPT-350M"?

### ISSUE THREAD

**Issue by Flywolfs** [microsoft/DeepSpeed#3288]
**Describe the bug**
I have tried the tutorial of DeepSpeed-Chat based on 1.3B model one(GPU:A6000).  The training command:
python train.py --actor-model facebook/opt-1.3b --reward-model facebook/opt-350m --deployment-type single_gpu

The training process is very successful without any error, but the inference result is truly bad and total nonsense. And more bad is, the inference process always crashed in the second round of chat. Does anybody occur this issue?

The inference command, I used the model from step3 as actor(**Is this correct?**):
python chat.py --path /root/DeepSpeedExamples/applications/DeepSpeed-Chat/output/step3-models/1.3b/actor

The inference result:
<img width="1090" alt="截屏2023-04-18 下午5 53 05" src="https://user-images.githubusercontent.com/10992547/232741306-01ca9053-d40c-4e00-8d1e-55002d254d78.png">

**Comment by LanShanPi** [comment]
my code: python chat.py --path /xxxx/DeepSpeedExamples/applications/DeepSpeed-Chat/output/step3-models/1.3b/actor/  and I got the follow error:
OSError: Can't load tokenizer for '/xxxx/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/1.3b'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/home/fm001/hzl/Project/DeepSpeedExamples/applications/DeepSpeed-Chat/output/actor-models/1.3b' is the correct path to a directory containing all relevant files for a BloomTokenizerFast tokenizer.
