### ISSUE TITLE
In the method get_instantiation_memory_required_per_gpu(), defined in https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/autotuning/autotuner.py, "optimizer_mem = num_params * (16 if fp16_enabled else 8)", Why optimizer_mem= 16 if fp16 enabled? Naively, if FP16 is used for the Adam optimizer, shouldn't the factor be 4, rather than 16?

### ISSUE THREAD

**Issue by xianglinliu01** [microsoft/DeepSpeed#3598]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**ds_report output**
Please run `ds_report` to give us details about your setup.

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by tjruwase** [comment]
@xianglinliu01, 
Optimizer state is fp32 whether training is fp16 or fp32. 

For fp16 training, the optimizer memory includes (master) weights, momentum, variance, and gradients.  Hence factor 16. 

For fp32 training, the optimizer memory includes only momentum and variance (since training weights and gradients are already fp32). Hence factor 8.
