### ISSUE TITLE
[REQUEST] DS inference does not support kernel injection of Megatron MoE GPT? (even when the implementations of container and policy are there)

### ISSUE THREAD

**Issue by taehyunzzz** [microsoft/DeepSpeed#3897]
Hi, the DS inference does not seem to support the Megatron MoE GPT (this [file](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/utils.py)) even when you guys have implemented the class for the [policy and container](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/module_inject/containers/megatron_gpt_moe.py).

Is there a reason why nowhere in the code support Megatron MoE GPT?
Is there a specific branch that implements and supports the conversion of Megatron MoE GPT for DS inference?

Thanks~

**Comment by lekurile** [comment]
Hi @taehyunzzz,

During the Inference Engine refactor effort in GH-2554, the concept of model-specific and feature-specific containers was introduced. The `DS_MegatronGPTMoEContainer` container can be thought of as a placeholder and has _not_ been extensively tested.

All of the MoE inference code pre-refactor is retained in this container and the corresponding `BaseTransformerMoEContainer` base MoE container, however, additional testing is required to verify its functionality, which is why the container is not included in our `policy_to_ds_container` mapping function.

There are plans to eventually get this integrated in the future. Also, any contributions enabling this feature by users are always appreciated :).

Thanks,
Lev

**Comment by lekurile** [comment]
Closing the issue for now, please feel free to open another issue if you'd like to follow up on this area. Thanks!
