### ISSUE TITLE
[Question] is checkpoint_event_prologue and checkpoint_event_epilogue equals to deepspeed.zero.GatheredParameters?

### ISSUE THREAD

**Issue by x54-729** [microsoft/DeepSpeed#4065]
Does `deepspeed.zero.GatheredParameters` have the same effect as `checkpoint_event_prologue` and `checkpoint_event_epilogue`?
```python
# zero 3
with deepspeed.zero.GatheredParameters(model.parameters):
    # do something
```

```python
# zero 3
engine.optimizer.checkpoint_event_prologue()
# do something
engine.optimizer.checkpoint_event_epilogue()
```
If not, what's the differences?

**Comment by tjruwase** [comment]
Please see the difference from the implementations below. 

![image](https://github.com/microsoft/DeepSpeed/assets/4271600/e4fb2d37-2a12-4989-9fa8-a194011e5c34)

**Comment by x54-729** [comment]
> Please see the difference from the implementations below.
> 
> ![image](https://user-images.githubusercontent.com/4271600/257214399-e4fb2d37-2a12-4989-9fa8-a194011e5c34.png)

`deepspeed.zero.GatheredParameters` will gather the parameters passed to the context, while `checkpoint_event_prologue` and `checkpoint_event_epilogue` will gather all the parameters under the threshold?

**Comment by tjruwase** [comment]
`checkpoint_event_prologue` will partition all parameters (including persistent parameters) in preparation for writing out sharded checkpoint files. The persistent parameters are those that are configured not to be sharded, typically because they are too small for the memory savings to justify the communication costs. This behavior is configurable through ds_config: 
![image](https://github.com/microsoft/DeepSpeed/assets/4271600/103ee5f3-cadc-4fe8-a6f8-6bc9066db1db)

`checkpoint_event_epilogue` will gather persistent parameters so that normal condition is restored for training.
