### ISSUE TITLE
[BUG] DeepSpeed AIO errors on Windows

### ISSUE THREAD

**Issue by DevManPGP** [microsoft/DeepSpeed#4179]
Microsoft Windows [Version 10.0.19045.3324]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Paul>pip install deepspeed
Collecting deepspeed
Using cached deepspeed-0.10.1.tar.gz (851 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [17 lines of output]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2'
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "C:\Users\Paul\AppData\Local\Temp\pip-install-qpleaow8\deepspeed_70d9fc0454d2430185371db808bdfe91\setup.py", line 165, in
abort(f"Unable to pre-compile {op_name}")
File "C:\Users\Paul\AppData\Local\Temp\pip-install-qpleaow8\deepspeed_70d9fc0454d2430185371db808bdfe91\setup.py", line 51, in abort
assert False, msg
AssertionError: Unable to pre-compile async_io
[WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
DS_BUILD_OPS=1
[WARNING] async_io requires the dev libaio .so object and headers but these were not found.
[WARNING] If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[WARNING] One can disable async_io with DS_BUILD_AIO=0
[ERROR] Unable to pre-compile async_io
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Paul>

**Comment by loadams** [comment]
@DevManPGP - The error above is due to the fact that Windows does not really support lib_aio that is used for the async_io operation in DeepSpeed.  You can work around this easily in one of two ways, 1) add `set DS_BUILD_AIO=0` before your `pip install DeepSpeed` command.  This will disable building that operation, which is what is causing the error and is shown, for example, in [our script](https://github.com/microsoft/DeepSpeed/blob/master/build_win.bat) for building from source on Windows.  2) you can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/about), which provides a Linux layer on top of Windows.   If you do not plan on using the aync_io operation, the first may be easier, though you'll need to set that environment variable in whatever terminal you are using on Windows (cmd.exe/PowerShell).  

And just a quick reminder if you hadn't already, the [Windows Installation](https://github.com/microsoft/DeepSpeed#windows) section of our README contains the other installation steps that are specific to Windows here.

Aditionally, I see the following warning in your code:
```
[WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
```

Could you confirm that your torch installation sees your Cuda installation?  You can do this by running the following command in python:
```
import torch
torch.cuda.is_available()
```

**Comment by earonesty** [comment]
got really close building deep speed but might give up:

i have cuda 12 installed and nvidia-smi works and pytorch works and is build with cuda support

- i made these changes to get this far in cpp_extension.py:
```
	    self.libraries=["cudart", "c10_cuda"]
        self.library_dirs=["c:/program files/NVidia GPU Computing Toolkit/CUDA/v12.2/lib/x64"]
```
and in the build_extension loop:

```
    self._add_compile_flag(extension, '-D__CUDA_ARCH__=800')
```

this gets me past many of the errors but now stuck with some fp_16 cuda asm issue:

```
building 'deepspeed.ops.quantizer.quantizer_op' extension
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc" -c csrc/quantization/dequantize.cu -o build\temp.win-amd64-cpython-311\Release\csrc/quantization/dequantize.obj -Icsrc/inc
ludes -IC:\Users\erik\deepserv\venv\Lib\site-packages\torch\include -IC:\Users\erik\deepserv\venv\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\erik\deepserv\venv\Lib\sit
e-packages\torch\include\TH -IC:\Users\erik\deepserv\venv\Lib\site-packages\torch\include\THC -IC:\Users\erik\deepserv\venv\include -IC:\Users\erik\.pyenv\pyenv-win\versions\3.11.3\include -
IC:\Users\erik\.pyenv\pyenv-win\versions\3.11.3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\M
icrosoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.
0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Ki
ts\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_s
uppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /
wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /
MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_ARCH__=600 -DTORCH_API_INCLU
DE_EXTENSION_H -DTORCH_EXTENSION_NAME=quantizer_op -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --use-local-env
dequantize.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include\cuda_fp16.hpp(1030): error: expected a ")"
  { __half val; asm("{  cvt.rn.f16.f64 %0, %1;}\n" : "=h"(*(reinterpret_cast<unsigned short *>(&(val)))) : "d"(a)); return val; }
                                                   ^

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include\cuda_fp16.hpp(1030): warning #549-D: variable "val" is used before its value is set
  { __half val; asm("{  cvt.rn.f16.f64 %0, %1;}\n" : "=h"(*(reinterpret_cast<unsigned short *>(&(val)))) : "d"(a)); return val; }

```

**Comment by loadams** [comment]
Hi @earonesty - I know we are still seeing some Cuda 12 issues, even on Linux.  In particular, mismatches between the cuda installed verison and torch+Cuda versions of 12.1 and 12.2.  

Are things able to build with all ops disabled (I know this isn't a useful case, but curious on overall success there)?  Something like `DS_BUILD_OPS=0 pip install deepspeed` or even with `DS_BUILD_UTILS=1` in addition to that?

**Comment by earonesty** [comment]
correct, that works fine

**Comment by earonesty** [comment]
made a pr: https://github.com/microsoft/DeepSpeed/pull/4203

**Comment by loadams** [comment]
Thanks @earonesty - though to confirm, that doesn't fix the AIO issues that @DevManPGP brought up, this will help with the other ops that are supported on Windows though.

**Comment by earonesty** [comment]
yeah, agreed.   this was just the ticket i used to get that far!

**Comment by loadams** [comment]
Thanks @earonesty - we will review the PR, want to make sure we get it working for Windows users but get the right portable solution too.  I'll follow up on your PR.

@DevManPGP - are you still hitting this issue?  Were you able to see if torch sees your Cuda install?

**Comment by xsailor511** [comment]
How can this happen?Deepspeed from Microsoft is not support windows.

> Thanks @earonesty - we will review the PR, want to make sure we get it working for Windows users but get the right portable solution too. I'll follow up on your PR.
> 
> @DevManPGP - are you still hitting this issue? Were you able to see if torch sees your Cuda install?

**Comment by DevManPGP** [comment]
I gave up. I am using C++ in visual Studio 2022 instead of Python. It seems Python uses too many 3rd party apps and modules, developed by different companies with no common denominator shell to handle incompatibilities. If I develop in VS C++ on windows, the OS makes sure things work for me.

**Comment by loadams** [comment]
@xsailor511 - DeepSpeed supports Windows, though there may be changes required like those pointed out in this thread with the linked PR.  Additionally we have Windows installation directions on our README [here](https://github.com/microsoft/DeepSpeed#windows).  However, DeepSpeed leverages a number of other features and libraries that are not all compatible on Windows, so those features are unsupported.  

@DevManPGP - sorry that we were not able to help your build problems here, the python ecoystem is certainly very different from the C++ one especially on Windows and compared to Visual Studio.  If you decide to try python/DeepSpeed again, please open other issues if you have them and we can try to take a look.

I'll close this issue for now, and follow up with @earonesty on the PR.  @xsailor511 - if you have build problems, could you create a new issue, since the title on this one is no longer relevant to the conversation?
