### ISSUE TITLE
Does PipelineModule support pipelining across machines?

### ISSUE THREAD

**Issue by eric-haibin-lin** [microsoft/DeepSpeed#434]
Does PipelineModule support pipelining across machines? If not, what is the caveat? Thanks!

**Comment by ShadenSmith** [comment]
Yep! We scaled it to 800 GPUs (50 DGX-2 nodes) in our recent [trillion-parameter result](https://www.microsoft.com/en-us/research/blog/deepspeed-extreme-scale-model-training-for-everyone/). On machines with low inter-node bandwidth, we showed up to 7x speedup on GPT-2 sized problems by pipelining across machines.

By default, DeepSpeed prioritizes placing model- and data-parallel groups within a machine due to their larger communication volume, and then to pipeline across machines where bandwidth is lower. The exact placement will depend on the number of GPUs in a machine and the various degrees of parallelism.
