### ISSUE TITLE
Running onebitadam tests

### ISSUE THREAD

**Issue by david-macleod** [microsoft/DeepSpeed#443]
Hi 

I have tried running the tests for 1-bit Adam 
```
cd tests/onebitadam
pytest test_com_reduce_host.py
```
But it just returns 
```collecting ... %```

So I was wondering if I should be calling the tests in a different way?

**Comment by tjruwase** [comment]
@david-macleod Can you please run pytest in verbose mode?
`pytest -v -s test_com_reduce_host.py`

**Comment by david-macleod** [comment]
Thanks, that revealed an error with my mpi installation which I have now fixed and the tests now pass. I was wondering if it is possible to run the test across multiple nodes as it currently looks like it is only using a single process on a single node (using the above command)

**Comment by tjruwase** [comment]
Glad to hear the test is working for you. I don't have experience running pytest across nodes. 

@jeffra  or @ShadenSmith, do you have any ideas on this?

**Comment by david-macleod** [comment]
Perhaps I don't need pytest at all as my main motivation here is to run a performance test comparing PyTorch native DDP AllReduce with onebitadam, to see what (speed) gains I'd get on my particular topology. I initially thought modifying the unit test would be a quick way of achieving this, but in retrospect maybe I should just run some of the deepspeed example scripts with/without onebitadam enabled. Thank you for your help.

**Comment by jeffra** [comment]
Hi @david-macleod, you should be able to run the tests in https://github.com/microsoft/DeepSpeed/tree/master/tests/onebitadam without `pytest` since they're actually not traditional unit tests (unfortunately). We typically run them with `mpirun` or the `deepspeed` launcher directly which would support running across multiple nodes. As you just posted now, checking out the examples is probably also a good way to start here.

https://www.deepspeed.ai/tutorials/onebit-adam/

**Comment by david-macleod** [comment]
Thanks @jeffra I will try that
