### ISSUE TITLE
facing issue while running finetuning script (v1.5 - lora)

### ISSUE THREAD

**Issue by csvlrs-lak** [microsoft/DeepSpeed#4597]
got this error while executing scripts/v1_5/finetune_lora.sh 

FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin'

**Comment by loadams** [comment]
@csvlrs-lak - does the file exist on your system when you look in that path?  

Where did the scripts/v1_5/finetune_lora.sh script come from, since it is not in the DeepSpeed repository, is it this [one](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh)?  If so, you may need to check on their steps/directions for how to get that checkpoint, but the issue is not with DeepSpeed.
