### ISSUE TITLE
[REQUEST] dockerfile update

### ISSUE THREAD

**Issue by yongjer** [microsoft/DeepSpeed#4763]
**Describe the solution you'd like**
base image, python3, PyTorch, etc. update to the latest version

**Comment by loadams** [comment]
Hi @yongjer - what issues are you seeing with the [Dockerfile](https://github.com/microsoft/DeepSpeed/blob/master/docker/Dockerfile) that we provide in the repo?

**Comment by yongjer** [comment]
Like pytorch 2.1, cuda update to 12.1-ubuntu2204, and the library like TensorFlow can be removed or updated to TF2. Mellanox ofed, nv_peer_mem and openmpi seem to have a new version. python update to 3.11.

Basically to raised the issue because I want to install the latest transformers library but it can only install v4.19, I'm not sure what is a problem with, PyTorch or python3 version I guess

**Comment by yongjer** [comment]
Or maybe can change the base image to PyTorch instead of Cuda

**Comment by loadams** [comment]
Hi @yongjer - the dockerfile we provide in the repo is more of an example than one that is expected to work and kept up to date with the latest versions of everything.  We should update it with some of those dependencies that have moved to newer versions.  But for your workflows, I would recommend using your own Dockerfile with your dependencies rather than this one.

If you are still hitting errors with your own, can you share with us?
