### ISSUE TITLE
Questions about `ignore_unused_parameters`

### ISSUE THREAD

**Issue by keunwoochoi** [microsoft/DeepSpeed#4948]
Hi, I have some questions about `ignore_unused_parameters` parameter

1. According to the doc, it's relevant to Stage 2 only.
> Unused parameters in modules may be unexpected in static networks, but could be normal in dynamic networks. This controls whether or not training should terminate with an error message when unused parameters are detected. This is set to False by default, which means unused parameters are ignored and training continues. Now is just used in stage 2.

Is it true? I am asking because I have failed, possibly at a certain batch, when training a multimodel model with Deepspeed Stage 1. There can be a batch that has no images at all (I'll certainly look into the data too!) and I am wondering if controlling `ignore_unused_parameters` could be helpful. (It's possibly related: https://github.com/huggingface/accelerate/issues/2194)

2. What is the exact default value? I left a comment about it in this thread https://github.com/microsoft/DeepSpeed/pull/4418. Mentioning it because I'dd like to know the correct value anyways.

**Comment by loadams** [comment]
Hi @keunwoochoi - 

1. This should apply to stage 2 only, but controlling this parameter shouldn't be related, mostly because this should already be true by default (as shown below), but also this just controls an assertion if you're trying to check for unused parameters, link [here](https://github.com/microsoft/DeepSpeed/blob/13d84b4912492d40b68f4da7bc570e47b54bce2a/deepspeed/runtime/zero/stage_1_and_2.py#L1276C1-L1287C24).  

2. The correct default value is `true`, I corrected the inconsistency in the docs [here](https://github.com/microsoft/DeepSpeed/pull/4949), and the link to where this is set is [here](https://github.com/microsoft/DeepSpeed/blob/13d84b4912492d40b68f4da7bc570e47b54bce2a/deepspeed/runtime/zero/config.py#L242C4-L242C42).

**Comment by keunwoochoi** [comment]
@loadams thanks a lot for the quick and comprehensive answer!
