### ISSUE TITLE
Loading models with deepspeed_transformer_kernel=False  that were saved with deepspeed_transformer_kernel=True 

### ISSUE THREAD

**Issue by sriramiscool** [microsoft/DeepSpeed#498]
I have been using DeepSpeed to train the model. 
While training I use deepspeed_transformer_kernel which helps with effciency.
However, when I need to share the model with some one it requires them to use the kernel.
Is there a way for me to load the model into huggingface bert model?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @sriramiscool 

Thanks for trying out DeepSpeed. 
Yes, there is a way to convert the checkpoint from transformer kernel to huggingface. We have a convert script that does the opposite (from huggingface to DeepSpeed), however I am sure you can use this code to do the revrse for your case: https://github.com/microsoft/DeepSpeedExamples/blob/master/BingBertSquad/convert_bert_ckpt_to_deepspeed.py

Thanks,
Reza

**Comment by sriramiscool** [comment]
Hello Reza,
Thank you for the quick response.
This is great. I will take a look at it and see how it can be converted
and let you know if I run into any issues.

Thank you,
Sriram

**Comment by sriramiscool** [comment]
I was trying to convert the deepspeed model to BertForMaskedLM model in hugging face.
There are some keys that hugging face model has but no equivalent key exists in deepspeed and vice versa.
Keys in deepspeed without an equivalent in BertForMaskedLM:
bert.encoder.FinalLayerNorm.weight
bert.encoder.FinalLayerNorm.bias
bert.pooler.dense_act.weight
bert.pooler.dense_act.bias

Keys in BertForMaskedLM without an equivalent in deepspeed:
cls.predictions.decoder.bias
bert.embeddings.token_type_embeddings.weight

I understand that they need not be exactly the same, but would the right behavior during transformation be to ignore the weights for the first four keys and set the latter two to zeros?
Is there something else that needs to be done.
Please let me know.
Thanks,
Sriram

**Comment by RezaYazdaniAminabadi** [comment]
Hi Sriram,

Yes, you are right there are some differences. However, I don't think that's a good option to ignore these parameters difference.
There are two sources for such difference:
1. The transformer that you trained your model with is based on the Pre-LN architecture, which has a final layernorm at the end of the network. On the other hand, HuggingFace is based on Post-LN. 
2. Some of the parameters are named differently. For instance, bertpooler.dense (HuggingFace) and bertpooler.dense_act (DeepSpeed). This is due to fusing some operations together. 

Regarding the last parameter, you cannot find it since it was cancelled during the training (https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/nvidia/modelingpreln.py#L715). So, you probably can ignore this.

Thanks,
Reza

**Comment by sriramiscool** [comment]
Got it. Thanks a lot :)

**Comment by JoeyOhman** [comment]
Hi,

I am in the process of pre-training a BERT with DeepSpeed (Bing Bert), also leveraging the transformer kernel.

Is this still the recommended approach to convert a DeepSpeed trained model to HuggingFace? Does it happen to exist any DeepSpeed -> HuggingFace conversion scripts today?

Best Regards,
Joey
