### ISSUE TITLE
[BUG] Zero3 causes AttributeError: 'NoneType' object has no attribute 'numel' in continual training

### ISSUE THREAD

**Issue by thkimYonsei** [microsoft/DeepSpeed#5602]
I was training LLaVA model using deepspeed zero3. What I want to do is continually train the model to different datasets. 
I create LLaVA model and in the for-loop, I create new dataset and new trainer, then calls `trainer.train()`.
At the first iteration of the for-loop, the training works properly.
However, at the second iteration, I got 1 warning and 1 error:
warning: `"Invalidate trace cache @ step XX: expected module XX, but got module XX"`
error:  `AttributeError: 'NoneType' object has no attribute 'numel'` at the same location as this [issue](https://github.com/microsoft/DeepSpeed/issues/5019#issue-2101914020)

Screenshot:
![image](https://github.com/microsoft/DeepSpeed/assets/55945983/2d1468af-43d3-4902-bc3b-ca270eca9964)

![image](https://github.com/microsoft/DeepSpeed/assets/55945983/17dd5c03-c0e3-45c6-9995-d7d3c16b7973)

But when I simply change the deepspeed config to use zero2 instead of zero3, no error occurs.
I want to use zero3 for larger batch size training. Can you help me out with this?

**System info**
 - OS: Ubuntu 20.04
 - GPU count and types: single node 4 RTX A6000 gpus
 - Python version: 3.10.0

`zero3.json` that I used:
```json
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto"
    },
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    }
}
```
zero2.json
```json
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto"
    },
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 2,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto"
    }
}
```

**Comment by Xirid** [comment]
I have the same issue and solved it by just reloading the whole model on every iteration. 
Though now I am getting oom due to the memory not freeing after the second epoch, but I guess that is a different issue.

**Comment by tjruwase** [comment]
@Xirid, please try the following API to free engine memory
https://deepspeed.readthedocs.io/en/latest/zero3.html#gpu-memory-management

**Comment by apToll** [comment]
我也遇到了在 for 循环中创建新的数据集和新的训练器，然后调用trainer.train()。
在 for 循环的第一次迭代中，训练工作正常。然而，在第二次迭代中，报错为错误： AttributeError: 'NoneType' object has no attribute 'numel'
尝试释放GPU，但没有用，释放GPU如下：# Free GPU memory consumed by model parameters
ds_engine.empty_partition_cache()

**Comment by tjruwase** [comment]
Closing this issue due to lack of response. Please reopen if needed.

**Comment by cindy2000sh** [comment]
Hi @tjruwase are there any updates on this issue? I met the same problem with this same setup here from @thkimYonsei :

> I create LLaVA model and in the for-loop, I create new dataset and new trainer, then calls trainer.train().
At the first iteration of the for-loop, the training works properly.

The only difference is I use gemma for training. And this issue exactly arises when the 2nd training iteration starts.

**Comment by apToll** [comment]
I have encountered similar issues before, but I couldn't resolve them. I suspect it may be due to the parameter partitioning in zero3 stage, which could cause errors during return (for example, if a deep copy was made and the previous parameters were deleted).

Additionally, I suggest that you directly save the model and then conduct the two-stage training. On one hand, the original model requires you to debug it yourself, and I'm not sure if you have enough computational power (as I previously used a remote server at Baidu, which was a tidal service); on the other hand, I suspect that the Llama model does not release the cache from the previous stage, which I think could be a significant problem.

Finally, I wish you success in resolving the issue!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepspeedai/DeepSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月10日(星期一) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepspeedai/DeepSpeed] [BUG] Zero3 causes AttributeError: 'NoneType' object has no attribute 'numel' in continual training (Issue #5602)



   
Hi @tjruwase are there any updates on this issue? I met the same problem with this same setup here from @thkimYonsei :
  
I create LLaVA model and in the for-loop, I create new dataset and new trainer, then calls trainer.train().
 At the first iteration of the for-loop, the training works properly.
  
The only difference is I use gemma for training. And this issue exactly arises when the 2nd training iteration starts.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  cindy2000sh left a comment (deepspeedai/DeepSpeed#5602)
 
Hi @tjruwase are there any updates on this issue? I met the same problem with this same setup here from @thkimYonsei :
  
I create LLaVA model and in the for-loop, I create new dataset and new trainer, then calls trainer.train().
 At the first iteration of the for-loop, the training works properly.
  
The only difference is I use gemma for training. And this issue exactly arises when the 2nd training iteration starts.

**Comment by apToll** [comment]
I did not resolve this issue, and I was only an intern at Baidu, so I couldn't take any documents away from Baidu. This is my reply to another person:

I have encountered similar issues before, but I couldn't resolve them. I suspect it may be due to the parameter partitioning in zero3 stage, which could cause errors during return (for example, if a deep copy was made and the previous parameters were deleted).

Additionally, I suggest that you directly save the model and then conduct the two-stage training. On one hand, the original model requires you to debug it yourself, and I'm not sure if you have enough computational power (as I previously used a remote server at Baidu, which was a tidal service); on the other hand, I suspect that the Llama model does not release the cache from the previous stage, which I think could be a significant problem.

Finally, I wish you success in resolving the issue!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepspeedai/DeepSpeed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月10日(星期一) 晚上11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deepspeedai/DeepSpeed] [BUG] Zero3 causes AttributeError: 'NoneType' object has no attribute 'numel' in continual training (Issue #5602)



    
Hi @tjruwase are there any updates on this issue? I met the same problem with this same setup here from @thkimYonsei :
  
@cindy2000sh, can you please confirm that you are using the latest DS since we have merged some related fixes. Also, are you able to share a full repro? Thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  tjruwase left a comment (deepspeedai/DeepSpeed#5602)
  
Hi @tjruwase are there any updates on this issue? I met the same problem with this same setup here from @thkimYonsei :
  
@cindy2000sh, can you please confirm that you are using the latest DS since we have merged some related fixes. Also, are you able to share a full repro? Thanks!
