### ISSUE TITLE
when I finetune the model use deepspeed on 2 4*A800s，log only contain worker1

### ISSUE THREAD

**Issue by bill4689** [microsoft/DeepSpeed#5809]
when I finetune the model use deepspeed on 2 A800，log only contain worker1，no worker2.
Is there any way to print the loss of Worker2? The GPUs on both machines are running normally, and the GPU memory is floating normally。
The script I use

![image](https://github.com/user-attachments/assets/10278c41-6799-4ca8-81d5-1732c15b7e1d)

The zero2.json I use

![image](https://github.com/user-attachments/assets/40b0652a-b042-4e04-b1e1-2faf9a08f27f)
   

The log
![image](https://github.com/user-attachments/assets/e2a3b73a-9abf-4d28-9c19-5896603c25d2)

**Comment by tjruwase** [comment]
@bill4689, do you know which code is generating those outputs? I don't believe it is DeepSpeed because DeepSpeed is unaware of epochs. Can you please try to locate the source of the outputs? 

Regardless, you can pass `--enable_each_rank_log <folder>` to your deepspeed launch command to enable logs for each rank. You can invoke `deepspeed -h` to see all the launcher options.

**Comment by loadams** [comment]
@bill4689 - following up on this if you have any updates?

**Comment by tjruwase** [comment]
Closing for lack of response. Please feel to re-open as needed.
