### ISSUE TITLE
Possible bug with layernorm kernel

### ISSUE THREAD

**Issue by owmohamm** [microsoft/DeepSpeed#581]
In this line https://github.com/microsoft/DeepSpeed/blob/1e44d48d5377a5f839c53ccefcd6951625479f51/csrc/transformer/normalize_kernels.cu#L198
epsilon is added to the variance. As far as I can tell the value of epsilon is 1e-12. Right after, the variance is converte to float16. When that is done the effect of epsilon is lost i.e. if the variance was zero then after adding epsilon it would be 1e-12 and after converting to float16 it would become 0 and the inverse square root operation 
https://github.com/microsoft/DeepSpeed/blob/1e44d48d5377a5f839c53ccefcd6951625479f51/csrc/transformer/normalize_kernels.cu#L211
would lead to NaNs. This causes issues when padding with zeros or a constant leading to NaNs in the forward pass.

**Comment by RezaYazdaniAminabadi** [comment]
Hi Owais,

This is very interesting. Yes, I think you are right, this may cause some NaNs in the case of variance becoming zero. I think the solution would be to just do this part of computation only in FP32. Vals_f can be divided here https://github.com/microsoft/DeepSpeed/blob/1e44d48d5377a5f839c53ccefcd6951625479f51/csrc/transformer/normalize_kernels.cu#L210 before converting to FP16. Also we need to save the variance in FP32: https://github.com/microsoft/DeepSpeed/blob/1e44d48d5377a5f839c53ccefcd6951625479f51/csrc/transformer/normalize_kernels.cu#L205, otherwise this can cause the same issue in the backward.
Thanks for finding this corner case! If you want you can do the changes and make a PR. I will also take care of doing some changes in the Normalize API to save the variance in FP32.

Reza

**Comment by owmohamm** [comment]
Hello Reza,
I haven't writing cuda kernels before so I'm a bit apprehensive of making the changes lest I introduce some other issues. I'd appreciate if you or anyone else from the deepspeed team could commit a fix for the bug.

Thanks!

**Comment by RezaYazdaniAminabadi** [comment]
Hi Owais,

No worries. I will take care of it and send you the PR so that you can review.

Thanks.
Reza

**Comment by owmohamm** [comment]
That'd be great, Thanks alot!
