### ISSUE TITLE
Why is cpu_optimizer flag decoupled from the deepspeed config JSON?

### ISSUE THREAD

**Issue by g-karthik** [microsoft/DeepSpeed#603]
https://github.com/microsoft/DeepSpeed/blob/41db1c2f033b82485a3ef7bd0a986d1a1b579519/tests/model/Megatron_GPT2/run_func_test.py#L237

Why is this flag decoupled from the deepspeed config JSON?

Also, where exactly does the `DeepSpeedEngine` parse this flag? I don't see its usage anywhere - it doesn't seem to be a supported arg in `_add_core_arguments()`, nor is it defined in `constants.py`.

@jeffra

**Comment by tjruwase** [comment]
Those are client model arguments and are used to configure our model tests (as opposed to unit tests).  The specific flag `cpu_optimizer` is used by Megatron_LM [here](https://github.com/microsoft/DeepSpeedExamples/blob/35b4582486fe096a5c669b6ca35a3d5c6a1ec56b/Megatron-LM/arguments.py#L63-L64).

**Comment by g-karthik** [comment]
@tjruwase ah I see, thanks! So leveraging ZeRO-Offload external to Megatron-LM doesn't require this flag, as I'd suspected. I am doing some debugging of ZeRO-Offload behavior external to Megatron-LM and this came up in that context.

Btw, where is it being read in `pretrain_gpt2.py`, I figure it should be used in [here](https://github.com/microsoft/DeepSpeedExamples/blob/35b4582486fe096a5c669b6ca35a3d5c6a1ec56b/Megatron-LM/pretrain_gpt2.py#L99), right?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @g-karthik,

This flag previously existed and we chose on the optimizer type at the same place you mentioned in pretrain_gpt2.py, however, we then decided to move this to the deepspeed config, so that we can differentiate between different optimizers when initializing deepspeed engine. We select between different optimizers based on this [table](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/engine.py#L643-L647).

Thanks,
Reza

**Comment by g-karthik** [comment]
@RezaYazdaniAminabadi makes sense, and gotcha, okay, I guess the `run_func_test.py` is just outdated then.

Thanks for your quick responses, appreciate it!
