### ISSUE TITLE
[docs] https://deepspeed.readthedocs.io doesn't have API docs

### ISSUE THREAD

**Issue by stas00** [microsoft/DeepSpeed#605]
The main site sends to https://deepspeed.readthedocs.io for API docs, but the latter appears to be pretty much a placeholder with a few almost empty pages and contains no API docs whatsoever.

Is that a bug, or the whole thing is under construction? If the latter perhaps it'd help to indicate that - otherwise it suggests that your API docs generator is broken.

Thank you.

**Comment by leosaturnin** [comment]
It's under construction   On Wednesday, December 16, 2020, 01:55:56 AM GMT+5:30, Stas Bekman <notifications@github.com> wrote:  
 
 


The main site sends to https://deepspeed.readthedocs.io for API docs, but the latter appears to be pretty much a placeholder with a few almost empty pages and contains no API docs whatsoever.

Is that a bug, or the whole thing is under construction? If the latter perhaps it'd help to indicate that - otherwise it suggests that your API docs generator is broken.

Thank you.

**Comment by jeffra** [comment]
Hi @stas00 and @leosaturnin, so sorry. Our read the docs page broke recently and we're working on fixing it. Will update this thread when it's fixed.

**Comment by jeffra** [comment]
Should be fixed now.

**Comment by stas00** [comment]
excellent! thank you for the quick fix, @jeffra!
