### ISSUE TITLE
[BUG] Unnecessary memory copy in paramater partition in ZeRO3

### ISSUE THREAD

**Issue by yingtongxiong** [microsoft/DeepSpeed#6804]
**Describe the bug**
When I read the zero3 init code, I have some confusion about override apply function.  The partition here [https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L427](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L427) transmit the `has_been_updated` is True to the partition function. And I think at this time, the parameters have already been partitioned in __init__ function. Then, I look the partition function and want to know how to use the `has_been_updated` in here [https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L1561](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L1561). Therefore, I am very confused, since the parameters has already been partitioned in __init__ function, so the param.ds_tensor is not None will be True, however, if judgement will return False as the has_been_updated is True, then it will still conduct the following memory copy operation which is not necessary. I don't know if I am right? Can anyone help me with this?

**To Reproduce**
run a model, and add model.apply(fn)

**Comment by tjruwase** [comment]
@yingtongxiong, the code is written for a common usage of apply as described [here](https://github.com/microsoft/DeepSpeed/blob/f743feca033515fdded50a98093da5a48eb41e74/deepspeed/runtime/zero/partition_parameters.py#L377-L388). In such usage, only rank 0 performs the custom apply logic and `has_been_updated` is set to `True` to broadcast the updates while partitioning. You are correct that redundant copies could occur in usage patterns that deviate from this. However, we have not seen performance complaints, probably because this occurs during initialization.

**Comment by yingtongxiong** [comment]
@tjruwase Thank you for replying. I still don't understand this sentence: "In such usage, only rank 0 performs the custom apply logic, and has_been_updated is set to True to broadcast the updates while partitioning. "Do you mean that only rank 0 could override the apply function and then conduct broadcast?

**Comment by tjruwase** [comment]
> "Do you mean that only rank 0 could override the apply function and then conduct broadcast?

@yingtongxiong, yes that is correct.

**Comment by tjruwase** [comment]
@yingtongxiong, I hope the following link provides more context https://deepspeed.readthedocs.io/en/latest/zero3.html#overriding-module-apply
