### ISSUE TITLE
TensorBoardX is too old in requirements.txt

### ISSUE THREAD

**Issue by surak** [microsoft/DeepSpeed#789]
tensorboardX 1.8 is from mid 2019. Version 1.9 is from October, 2019, and there are 2.0. and 2.1 already. 

It's difficult to install legacy versions of softwares on our supercomputers just because of one software.

**Comment by aphedges** [comment]
I'm not really sure why it is pinned. Looking through the Git history, it seems that `tensorboardX==1.8` has been in `requirements.txt` since the file was added in 577295f.

I'm using a version of pip old enough to allow me to install conflicting dependencies, but this will be a problem once I update. There doesn't seem to be much direct usage of `tensorboardX` in the codebase, so I hope this will be an easy change for them (or for a user, if we need to do it ourselves).

**Comment by aphedges** [comment]
`tensorboardX` was removed as a direct dependency in a90497e, so this issue should be closed.
