### ISSUE TITLE
External parameter clarification

### ISSUE THREAD

**Issue by janEbert** [microsoft/DeepSpeed#930]
Hey, from both doc sites I have several questions regarding external parameters for ZeRO stage 3 usage.

When external parameters are involved in a model, is it possible that the code works even when they aren't registered? Would I get a warning? Or will my model fail silently? Or may it crash if my chosen parameters randomly partition the parameters the wrong way?

**Comment by samyam** [comment]
@janEbert in most cases if its not setup properly it will crash. If the parameter is partitioned when its about to be used, then the mismatch in shape will often cause it to crash. 

However, there are cases where there can be silent failures. partitioned parameters in ZeRO-3 are represented by a scalar value but the scaler values are broadcastable, so if a parameter is used in element wise operations, it can fail silently for example. 

We are thinking about what might be a good way to address this. One thing we have been thinking about is to use an odd shaped tensor to represent partitioned parameters, so that it will reduce the chances of silent failures.

For example:
Full parameter:
    param.data = [1024,1024]
Current partitioned parameter representation
    param.data = 1.0

Silent faliure case :
       result = torch.rand([1024,1024]) + param (this will fail silently because 1.0 is broadcastable to [1024,1024])

Possible fix using an alternate partitioned parameter representation
          param.data=[5,2,3] (some wierd shaped tensor)

So torch.rand([1024,1024]) + param will fail.

We will this to our TODO list, but very happy to get contributions.

**Comment by janEbert** [comment]
Hey @samyam, thank you for the detailed explanation! That really helps.
It sounds like the possibility of the program _not_ failing is rather low.

I still have to dive into the codebase to understand what is happening in the background better. For now, your answer definitely helps; if I get the time I'm happy to look into this further.

@cli99 are you going to add this to the documentation?

**Comment by cli99** [comment]
Hi @janEbert, I am working on a PR as @samyam suggested. https://github.com/microsoft/DeepSpeed/pull/981

**Comment by janEbert** [comment]
All right, thanks! Looking forward to stumbling upon some errors when you're done. ;)

**Comment by janEbert** [comment]
I just read this while informing myself about ZeRO-Infinity (in [./docs/_tutorials/zero.md](https://github.com/microsoft/DeepSpeed/blame/fbece50b21ffeb4fe05e498f930aded71de12aed/docs/_tutorials/zero.md#L240-L243)):
> Registering external parameters
> 
> Deprecated: DeepSpeed version 0.3.15 introduced automatic external parameter registration and this step is no longer needed.

I'll close this, then. Thanks for all your support!
